### ISSUE TITLE
Kafka Mirror Maker 2 fails to flush to Azure Event Hub when idle connections

### ISSUE THREAD

**Issue by ppatierno** [Azure/azure-event-hubs-for-kafka#105]
Description
===========
I am working on integrating Kafka Mirror Maker 2 (with the [Strimzi](http://strimzi.io) project) with Azure Event Hub.
I am able to do that but I noticed that if Kafka Mirror Maker 2 isn't mirroring a steady stream of data, at some point it stops to work.
What I mean is that ...
If I send a message on the local Kafka cluster, Mirror Maker 2 is able to mirror it to Event Hub.
Then if I don't wait to much time and send another message, it works again.
If I wait from 5 to 10 minutes to send another message, Mirro Maker 2 fails with following error in the log:

```shell
SourceTask{id=my-cluster->eventhub.MirrorSourceConnector-0} Failed to flush, timed out while waiting for producer to flush outstanding 1 messages (org.apache.kafka.connect.runtime.WorkerSourceTask) [SourceTaskOffsetCommitter-1]
2020-05-19 08:49:06,555 ERROR WorkerSourceTask{id=my-cluster->eventhub.MirrorSourceConnector-0} Failed to commit offsets (org.apache.kafka.connect.runtime.SourceTaskOffsetCommitter) [SourceTaskOffsetCommitter-1]
```

After quite a while it seems to recover restarting to mirror the pending messages to Event Hub.
This doesn't happen if I produce a steady stream of messages (i.e. 1 msg/sec).

My question is: is it possible that Event Hub somehow closes idle connections but there is no evidence in the MM2 log? What are the policy for Event Hub using the Kafka protocol here?

Thanks.

How to reproduce
================
Not so simple but following this blog [post](https://strimzi.io/blog/2020/05/14/mirror-kafka-eventhub/) and using MM2 instead of MM1 with this [YAML](https://github.com/ppatierno/strimzi-eventhub/blob/master/kubernetes/kafka-mirror-maker-2.yaml).

Has it worked previously?
=========================
No

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed or where adequate information has not been provided.

Please provide the relevant information for the following items:
 - [ ] SDK (include version info): `<REPLACE with e.g., kafka-python/Java SDK/confluent-kafka-dotnet with version info>`
 - [ ] Sample you're having trouble with: `<REPLACE with e.g., Java quickstart>`
 - [x] If using Apache Kafka Java clients or a framework that uses Apache Kafka Java clients, version: `<REPLACE with e.g., 1.1.0>`
 - [ ] Kafka client configuration: `<REPLACE with e.g., auto.reset.offset=earliest, ..>` (*do not include your connection string or SAS Key*)
 - [ ] Namespace and EventHub/topic name
 - [ ] Consumer or producer failure `<REPLACE with e.g., Consumer failure>`
 - [ ] Timestamps *in UTC* `<REPLACE with e.g., Nov 7 2018 - 17:15:01 UTC>`
 - [ ] group.id or client.id `<REPLACE with e.g., group.id=cg-name>`
 - [ ] Logs provided (with debug-level logging enabled if possible, e.g. log4j.rootLogger=DEBUG) or exception call stack
 - [ ] Standalone repro `<REPLACE with e.g., Willing/able to send scenario to repro issue>`
 - [ ] Operating system: `<REPLACE with e.g., Ubuntu 16.04.5 (x64) LTS>`
 - [ ] Critical issue

If this is a question on basic functionality, please verify the following:
 - [ ] Port 9093 should not be blocked by firewall ("broker cannot be found" errors)
 - [ ] Pinging FQDN should return cluster DNS resolution (e.g. `$ ping namespace.servicebus.windows.net` returns ~ `ns-eh2-prod-am3-516.cloudapp.net [13.69.64.0]`)
 - [ ] Namespace should be either Standard or Dedicated tier, not Basic (TopicAuthorization errors)

**Comment by arerlend** [comment]
Have you tried setting the recommended Java configs from the configuration doc at the root of this repo?

**Comment by ppatierno** [comment]
I was just going to update the issue ...
I tried changing `metadata.max.age.ms` and `connections.max.idle.ms` on the MirrorSourceConnector producer to the suggested values, but nothing was helpful.

**Comment by arerlend** [comment]
If a producer TCP connection stays idle for more than four minutes, connection may be closed.  The producer timeouts are often caused by sending on dead TCP connection.  https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-tcp-idle-timeout#tcp-idle-timeout

Setting max connection idle timeout means that the producer will proactively close idle connections.  When the next send operation happens, a new TCP connection will be negotiated.

**Comment by arerlend** [comment]
How are you setting the configurations?  Do the configs make it into the task configurations when you start the connectors?

**Comment by ppatierno** [comment]
This is actually what I get as connector configuration:

```shell
curl -s "http://localhost:8083/connectors/my-cluster->eventhub.MirrorSourceConnector" | jq
{
  "name": "my-cluster->eventhub.MirrorSourceConnector",
  "config": {
    "target.cluster.status.storage.replication.factor": "1",
    "connector.class": "org.apache.kafka.connect.mirror.MirrorSourceConnector",
    "offset-syncs.topic.replication.factor": "1",
    "replication.factor": "1",
    "target.cluster.sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"$ConnectionString\" password=\"${file:/tmp/strimzi-mirrormaker2-connector.properties:eventhub.sasl.password}\";",
    "sync.topic.acls.enabled": "false",
    "target.cluster.sasl.mechanism": "PLAIN",
    "topics": ".*",
    "target.cluster.config.storage.replication.factor": "1",
    "source.cluster.alias": "my-cluster",
    "producer.connections.max.idle.ms": "180000",
    "groups": ".*",
    "source.cluster.bootstrap.servers": "my-cluster-kafka-bootstrap:9092",
    "target.cluster.offset.storage.replication.factor": "1",
    "target.cluster.alias": "eventhub",
    "target.cluster.security.protocol": "SASL_SSL",
    "name": "my-cluster->eventhub.MirrorSourceConnector",
    "producer.metadata.max.age.ms": "180000",
    "target.cluster.bootstrap.servers": "functiontesteh.servicebus.windows.net:9093"
  },
  "tasks": [
    {
      "connector": "my-cluster->eventhub.MirrorSourceConnector",
      "task": 0
    }
  ],
  "type": "source"
}
```

and in the log I can see these values being reflected on the producer configuration:

```shell
2020-05-26 16:26:31,179 INFO ProducerConfig values: 
	acks = 1
	batch.size = 16384
	bootstrap.servers = [my-cluster-kafka-bootstrap:9092]
	buffer.memory = 33554432
	client.dns.lookup = default
	client.id = producer-4
	compression.type = none
	connections.max.idle.ms = 180000
	delivery.timeout.ms = 120000
	enable.idempotence = false
	interceptor.classes = []
	key.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
	linger.ms = 0
	max.block.ms = 60000
	max.in.flight.requests.per.connection = 5
	max.request.size = 1048576
	metadata.max.age.ms = 180000
	metadata.max.idle.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
	receive.buffer.bytes = 32768
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retries = 2147483647
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	security.providers = null
	send.buffer.bytes = 131072
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2]
	ssl.endpoint.identification.algorithm = https
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLSv1.2
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	transaction.timeout.ms = 60000
	transactional.id = null
	value.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
 (org.apache.kafka.clients.producer.ProducerConfig) [task-thread-my-cluster->eventhub.MirrorSourceConnector-0]
```

**Comment by arerlend** [comment]
What are your connect worker settings?  The original error message actually seems to indicate that it's the task offset committer that is failing to flush.  

https://kafka.apache.org/documentation/#connectconfigs shows default worker connection max idle timeout as 540s.

**Comment by arerlend** [comment]
Just added them to the doc. 

https://github.com/Azure/azure-event-hubs-for-kafka/commit/f796795cf80046e932e5fa1a4cb8306157ff11c8

**Comment by ppatierno** [comment]
Actually, if you see here 

https://github.com/apache/kafka/blob/trunk/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerSourceTask.java#L448

The worker source task is trying to commit offset but there are outstanding messages to send which are failing so the message "Failed to flush, timed out ..." so the problem is about flushing messages to send not offsets to commit.

**Comment by ppatierno** [comment]
Instead of setting that configuration at source connector level I did at Connect level but the results is always the same. I am run out of ideas. My Kafka cluster with Kafka Mirror Maker 2 is running on OpenShift locally (minishift) and as I mentioned using Strimzi. Days ago I also tried using Kubernetes locally, AKS and OCP 4.x but same result. I will try to run a Kafka cluster on bare metal, even if I cannot see how it could make a difference.

**Comment by arerlend** [comment]
How large messages are you sending?  Can you set max.request.size to recommended value?

At this point it may be worth creating a service ticket against the EH team so we can spend more time checking the issue.

**Comment by ppatierno** [comment]
They are just messages like "Hello", "World", ... sent using the `kafka-console-producer` to the Kafka cluster and read by `kafka-console-consumer` via EH.

**Comment by ppatierno** [comment]
Finally I fixed it. The missing configuration was about `metadata.max.age.ms` and `connections.max.idle.ms` but on the producer Kafka Connect side, not the source connector. I was also missing the `producer.` prefix for configuring them accordingly.
Anyway, as I wrote a blog post about using MM1 (https://strimzi.io/blog/2020/05/14/mirror-kafka-eventhub/), I will write a new one about using MM2 over the next weekend.
Thanks for your help!

**Comment by arerlend** [comment]
Thanks for the update.  Feel free to post a new link, would like to check it out.

**Comment by ppatierno** [comment]
@arerlend FYI https://strimzi.io/blog/2020/06/09/mirror-maker-2-eventhub/

**Comment by MarekLani** [comment]
For people searching the Mirror Maker 2 blog it is here: https://strimzi.io/blog/2020/06/09/mirror-maker-2-eventhub/  @ppatierno  thank you
