### ISSUE TITLE
Using IOT Event Hub for Kafka Unknown topic or partition

### ISSUE THREAD

**Issue by marcobocca1973** [Azure/azure-event-hubs-for-kafka#117]
Hi,

Could you help me to wit that ? I'm using .Net Core example but It seem the topi could not create.
It seems looking in azure that the request is arriving, i don't understand ?

![image](https://user-images.githubusercontent.com/47218182/95471639-7186f300-0982-11eb-9585-619b37d65a90.png)

Initializing Producer
Sending 10 messages to topic: test, broker(s): kafkabroker.servicebus.windows.net:9093
Exception Occurred - Broker: Unknown topic or partition

Initializing Consumer
Consuming messages from topic: test, broker(s): kafkabroker.servicebus.windows.net:9093
Consume error: Broker: Unknown topic or partition

Thank you

marco

**Comment by arerlend** [comment]
Hi @marcobocca1973 - rdkafka libraries do not support topic auto-creation.  Can you try explicitly creating the topic?

**Comment by arerlend** [comment]
rdkafka relies on broker settings to determine whether topic auto-creation and does not include topic auto-creation flag.  However, EH will examine the metadata request for a topic auto-creation flag.

Thus, resolution for rdkafka libraries is to explicitly create the topic in portal/Kafka admin client/EH client library.
