### ISSUE TITLE
Can't consume eventhubs with go oauth tutorial sample

### ISSUE THREAD

**Issue by ernani** [Azure/azure-event-hubs-for-kafka#129]
Description
===========
Using go oauth sample can produce messages to a given eventhub but can't consume it.

How to reproduce
================
- Create a standard eventhubs.
- Create a service principal and grant appropriate rbac to a particular eventhub.
- Test the samples both producer and consumer.

Has it worked previously?
=========================
This is an attempt to test the given examples, so it didn't work before.

Checklist
=========

 - [x] Sample you're having trouble with: `oauth go tutorial`
 - [x] Kafka client configuration: `similar to the one in the example, but with my own eventhubs instance`
 - [x] Namespace and EventHub/topic name `test`
 - [x] Consumer or producer failure `consumer`
 - [x] group.id or client.id `$Default`
 - [x] Logs provided (with debug-level logging enabled if possible, e.g. log4j.rootLogger=DEBUG) or exception call stack
 %7|1608446184.333|PROTOERR|rdkafka#consumer-1| [thrd:sasl_ssl://ernani-standard.servicebus.windows.net:9093/bootstra]: sasl_ssl://xxxxx.servicebus.windows.net:9093/bootstrap: Protocol parse failure for ApiVersion v3 at 3/10 (rd_kafka_handle_ApiVersion:2003) (incorrect broker.version.fallback?)

 - [x] Operating system: `wsl with ubuntu 20`
 - [x] Critical issue

**Comment by VeitSanner** [comment]
@ernani, I am facing the same issue. Have you had any luck to get the Go example working?

**Comment by VeitSanner** [comment]
This seems to be related from which level the consumer application is granted the role `Azure Event Hubs Data Receiver`. When the role is granted from the Event Hubs Namespace the application can consume messages from the child Event Hubs. Although, there still seems to be a version mismatch:

```
%7|1625650494.658|INIT|rdkafka#consumer-1| [thrd:app]: librdkafka v1.7.0 (0x10700ff) rdkafka#consumer-1 initialized (builtin.features gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,zstd,sasl_oauthbearer, CC CXX PKGCONFIG OSXLD LIBDL PLUGINS ZLIB SSL SASL_CYRUS ZSTD HDRHISTOGRAM LZ4_EXT SYSLOG SNAPPY SOCKEM SASL_SCRAM SASL_OAUTHBEARER CRC32C_HW, debug 0x2000)
%7|1625650494.659|SUBSCRIBE|rdkafka#consumer-1| [thrd:main]: Group "foo": subscribe to new subscription of 1 topics (join-state init)
handleOAuthBearerTokenRefreshEvent***
%7|1625650495.457|PROTOERR|rdkafka#consumer-1| [thrd:sasl_ssl://bar.servicebus.windows.net:9093/bootstrap]: sasl_ssl://bar.servicebus.windows.net:9093/bootstrap: Protocol parse failure for ApiVersion v3(flex) at 3/10 (rd_kafka_handle_ApiVersion:2126) (incorrect broker.version.fallback?)
%7|1625650495.457|PROTOERR|rdkafka#consumer-1| [thrd:sasl_ssl://bar.servicebus.windows.net:9093/bootstrap]: sasl_ssl://bar.servicebus.windows.net:9093/bootstrap: ApiArrayCnt -1 out of range
%7|1625650496.213|PROTOERR|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator/0: Protocol parse failure for ApiVersion v3(flex) at 3/10 (rd_kafka_handle_ApiVersion:2126) (incorrect broker.version.fallback?)
%7|1625650496.213|PROTOERR|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator/0: ApiArrayCnt -1 out of range
%7|1625650496.387|JOIN|rdkafka#consumer-1| [thrd:main]: Group "foo": postponing join until up-to-date metadata is available
%7|1625650496.526|REJOIN|rdkafka#consumer-1| [thrd:main]: Group "foo": subscription updated from metadata change: rejoining group
%7|1625650496.526|REBALANCE|rdkafka#consumer-1| [thrd:main]: Group "foo" initiating rebalance (NONE) in state up (join-state wait-metadata) with 0 assigned partition(s): Metadata for subscribed topic(s) has changed
%7|1625650496.526|REJOIN|rdkafka#consumer-1| [thrd:main]: Group "foo": Rejoining group without an assignment: Metadata for subscribed topic(s) has changed
%7|1625650496.526|JOIN|rdkafka#consumer-1| [thrd:main]: sasl_ssl://bar.servicebus.windows.net:9093/0: Joining group "foo" with 1 subscribed topic(s)
%7|1625650496.813|ASSIGNOR|rdkafka#consumer-1| [thrd:main]: Group "foo": "range" assignor run for 1 member(s)
%7|1625650496.843|ASSIGN|rdkafka#consumer-1| [thrd:main]: Group "foo": new assignment of 1 partition(s) in join-state wait-assign-call
%7|1625650496.843|CLEARASSIGN|rdkafka#consumer-1| [thrd:main]: No current assignment to clear
%7|1625650496.843|ASSIGNMENT|rdkafka#consumer-1| [thrd:main]: Added 1 partition(s) to assignment which now consists of 1 partition(s) where of 1 are in pending state and 0 are being queried
%7|1625650496.843|OFFSET|rdkafka#consumer-1| [thrd:main]: GroupCoordinator/0: Fetch committed offsets for 1/1 partition(s)
%7|1625650496.901|FETCH|rdkafka#consumer-1| [thrd:main]: Partition ev1 [0] start fetching at offset 128
Message on ev1[0]@128: Welcome
Message on ev1[0]@129: to
Message on ev1[0]@130: the
Message on ev1[0]@131: Kafka
Message on ev1[0]@132: head
Message on ev1[0]@133: on
Message on ev1[0]@134: Azure
Message on ev1[0]@135: EventHubs
%7|1625650771.749|COMMIT|rdkafka#consumer-1| [thrd:main]: GroupCoordinator/0: Committing offsets for 1 partition(s) with generation-id 6 in join-state steady: cgrp auto commit timer

```

If the permissions are granted only at the Event Hubs Instance which hosts the topic, the application cannot consume any message. Because the message is nil, we get a n error when printing the consumer error in line 158.

https://github.com/Azure/azure-event-hubs-for-kafka/blob/013b9defcad7c8e79e57b791d3c2e88d6c531b2f/tutorials/oauth/go/consumer/consumer.go#L153-L161

The error is `1/1 brokers are down`.

@serkantkaraca what would be the proper way to connect to the event hub namespace when the consumer is only granted permissions on the Event Hubs Instance? 

The version for reproduction can be found here : https://github.com/VeitSanner/azure-event-hubs-for-kafka/tree/issues/consumer-cannot-connect/tutorials/oauth/go

**Comment by ernani** [comment]
I did fix the java and implemented a nodejs demo that uses OAUTH granularity per eventhub (topic), but didn't work on the go example.

I have been in touch with @serkantkaraca which provided the OAUTH implementation using the sarama lib, but haven't had the time to thoroughly test it.

If you could test the sarama version and let me know how it goes, that would be really helpful.

**Comment by serkantkaraca** [comment]
We are deploying a fix for entity level permission issue next week. Please let us know if you still hit the issue after then.
