### ISSUE TITLE
How to switch from EventHub to Kafka at a given offset?

### ISSUE THREAD

**Issue by dwoldo** [Azure/azure-event-hubs-for-kafka#130]
Description
===========
We are looking to migrate our consumers from EventHub to use the Kafka head. At present the consumer has check-pointed in Blob a set of offsets for each partition. I would like to switch my consumer to use Kafka at a specific offset to avoid duplicates/missed messages.

In doing this, a few questions:

1. Is the Kafka offset the same as the EventHub offset in terms of a 1:1, offset: 99912 in EH is offset: 99912 in Kafka?
2. Can we use `kafka-consumer-groups` to set the initial offset to be equal to EventHub?
3. Any concerns otherwise we should be aware of?

How to reproduce
================
N/A

Has it worked previously?
=========================
N/A

**Comment by arerlend** [comment]
Kafka offset is analagous to Event Hub sequence number.

I believe kafka-consumer-groups would work, but you can also start your Kafka consumer on offsets earliest for your new Kafka group, then seek to the required offset.

There shouldn't be any major concerns here.  I would just note that there are some differences between EH and Kafka groups; you can find them enumerated on the top level README in this repo.
