### ISSUE TITLE
SaslMechanism.OAuthBearer mechanism failing 

### ISSUE THREAD

**Issue by gurunathgopireddy** [Azure/azure-event-hubs-for-kafka#157]
Description
===========
OAUTH connection with Azure Event Hub

How to reproduce
================
Azure Event Hub with Kafka dot net and OAUTH mechanisam

Has it worked previously?
=========================
No

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed or where adequate information has not been provided.

Please provide the relevant information for the following items:
 - [ ] SDK (include version info): confluent-kafka-dotnet 1.70
 - [ ] Sample you're having trouble with: 
                SecurityProtocol = SecurityProtocol.SaslSsl,
                SaslMechanism = SaslMechanism.OAuthBearer,
 - [ ] Namespace and EventHub/topic name: efsoauthtest.servicebus.windows.net:9093
 - [ ] Consumer or producer failure producer failure
%7|1623264088.004|FAIL|1a7b1526-7051-4b3d-82dd-90c8ec4ab32d#producer-1| [thrd:sasl_ssl://efsoauthtest.servicebus.windows.net:9093/bootstrap]: sasl_ssl://efsoauthtest.servicebus.windows.net:9093/bootstrap: SASL authentication error: Invalid tenant name (after 133ms in state AUTH_REQ) (_AUTHENTICATION)
%3|1623264088.009|FAIL|1a7b1526-7051-4b3d-82dd-90c8ec4ab32d#producer-1| [thrd:sasl_ssl://efsoauthtest.servicebus.windows.net:9093/bootstrap]: sasl_ssl://efsoauthtest.servicebus.windows.net:9093/bootstrap: SASL authentication error: Invalid tenant name (after 133ms in state AUTH_REQ)
 - [ ] Logs provided (with debug-level logging enabled if possible, e.g. log4j.rootLogger=DEBUG) or exception call stack

 - [ ] Operating system: Windows
 - [ ] Critical issue: Yes

Azure App is returning Access Token but unable to connect azure event hub.

**Comment by serkantkaraca** [comment]
Can you ensure role assignments and app ID/secret all good as the first thing? 

I am also planning to add a sample with Confluent dotnet SDK so you can compare your code.

**Comment by gurunathgopireddy** [comment]
Yes, App ID and Secret are good. I can see access token returned from Azure, but not able to connect Event Hub.

IConfidentialClientApplication app = ConfidentialClientApplicationBuilder.Create(configOauth.ClientId)
                .WithClientSecret(configOauth.ClientSecret)
                .WithAuthority(new Uri(configOauth.Authority)) //Tenant Id
                .Build();
				
	   var resultBuilder = app.AcquireTokenForClient(scopes);
            var result = await resultBuilder.ExecuteAsync();

            const string principal = "consoleservice";
            void Callback(IClient client, string cfg)
            {
                client.OAuthBearerSetToken(result.AccessToken, result.ExpiresOn.ToUnixTimeMilliseconds(), principal);
            }
			
			using (var producer = new ProducerBuilder<string, string>(config).SetOAuthBearerTokenRefreshHandler(Callback).Build())
            {
                try
                {                    
                        // Note: Awaiting the asynchronous produce request below prevents flow of execution from proceeding until the acknowledgement from the broker is received
                        var deliveryResult = await producer.ProduceAsync(topicName, new Message<string, string> { Key = "1", Value = "Test Message" });
                }
                catch (ProduceException<string, string> e)
                {
                    Console.WriteLine($"failed to deliver message: {e.Message} [{e.Error.Code}]");
                }
            }

**Comment by serkantkaraca** [comment]
Where do you set the token request scope?

**Comment by gurunathgopireddy** [comment]
Below is complete code and I am new to Kafka. Please let me know, if I didn't set up correct configuration.


           string brokerList = "xxxx.servicebus.windows.net:9093";
            string topicName = "support";
            AuthenticationConfig configOauth = AuthenticationConfig.ReadFromJsonFile("appsettings.json");

            //The config variable does all the magic here, defining how the producer will connect to a kafka server (or in our case an event hubs instance using the kafka protocol)
            //The kafka protocol available for event hubs uses SASL(Simple Authentication and Security Layer) over SSL (SASL_SSL) as the security protocol,using plain username and password as the authentication method
            var config = new ProducerConfig()
            {
                BootstrapServers = brokerList,
                SecurityProtocol = SecurityProtocol.SaslSsl,
                SaslMechanism = SaslMechanism.OAuthBearer,
                Debug = "security"
            };

            // Even if this is a console application here, a daemon application is a confidential client application             
            IConfidentialClientApplication app = ConfidentialClientApplicationBuilder.Create(configOauth.ClientId)
                .WithClientSecret(configOauth.ClientSecret)
                .WithAuthority(new Uri(configOauth.Authority))
                .Build();

            // With client credentials flows the scopes is ALWAYS of the shape "resource/.default", as the 
            // application permissions need to be set statically (in the portal or by PowerShell), and then granted by
            // a tenant administrator
            string[] scopes = new string[] { configOauth.TodoListScope };
            var resultBuilder = app.AcquireTokenForClient(scopes);
            var result = await resultBuilder.ExecuteAsync();

            const string principal = "consoleservice";
            void Callback(IClient client, string cfg)
            {
                client.OAuthBearerSetToken(result.AccessToken, result.ExpiresOn.ToUnixTimeMilliseconds(), principal);
            }

            using (var producer = new ProducerBuilder<string, string>(config).SetOAuthBearerTokenRefreshHandler(Callback).Build())
            {
                try
                {
                    // Note: Awaiting the asynchronous produce request below prevents flow of execution from proceeding until the acknowledgement from the broker is received
                    var deliveryResult = await producer.ProduceAsync(topicName, new Message<string, string> { Key = "1", Value = "Test Message" });
                }
                catch (ProduceException<string, string> e)
                {
                    Console.WriteLine($"failed to deliver message: {e.Message} [{e.Error.Code}]");
                }
            }

**Comment by gurunathgopireddy** [comment]
After Service Principal name to , I am getting following error:

%7|1623335528.142|FAIL|rdkafka#producer-1| [thrd:sasl_ssl://efsoauthtest.servicebus.windows.net:9093/bootstrap]: sasl_ssl://efsoauthtest.servicebus.windows.net:9093/bootstrap: SASL authentication error: Invalid URI: The format of the URI could not be determined. (after 131ms in state AUTH_REQ) (_AUTHENTICATION)

**Comment by serkantkaraca** [comment]
Make sure your scope is in this format

"https://xxxx.servicebus.windows.net/.default"

**Comment by gurunathgopireddy** [comment]
Great; it worked 👍 

Thanks @serkantkaraca
