### ISSUE TITLE
I am getting following error "org.apache.kafka.common.errors.TopicAuthorizationException: Not authorized to access topics: [xxxxx]"

### ISSUE THREAD

**Issue by ashitabh** [Azure/azure-event-hubs-for-kafka#16]
I am getting error of authorization exception even after setting manage permission in kafka consumer
org.apache.kafka.common.errors.TopicAuthorizationException: Not authorized to access topics: [mytopic]

bootstrap.servers=xxx.servicebus.windows.net:9093
group.id=$Default
request.timeout.ms=60000
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://azeuneventhubkylo.servicebus.windows.net/;SharedAccessKeyName=xxx;SharedAccessKey=xxx=;EntityPath=mytopic";

**Comment by arerlend** [comment]
@ashitabh  - try using a namespace level access key instead of the Event Hub level access key. 

It'll look something more like this:
> sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://azeuneventhubkylo.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=.......=";

**Comment by ashitabh** [comment]
Thanks , it worked 
But giving namespace level access key will allow users to see all the event hubs in that namespace.

**Comment by basilhariri** [comment]
Event Hub level connection strings are currently not enabled in Event Hubs for Kafka. We plan to enable them in the next month or so, but for now the only way to connect to the Kafka head is to use the namespace level connection string.

**Comment by hho** [comment]
This doesn't work at all for me:

* I create a new Event Hub Namespace with Kafka support
* I clone this repository
* I put the FQDN and the (namespace's) connection string into the config
* When I try to run the quickstart sample I get `org.apache.kafka.common.errors.TopicAuthorizationException: Not authorized to access topics: [test]`. (The Event Hub `test` is getting automatically created, though)

It doesn't matter whether I'm trying to produce or to consume.

**Comment by basilhariri** [comment]
@hho This exception is variable enough that it might be worth opening your own issue and providing us with more information (there is an issue template that will ask for all the relevant info)

**Comment by czyzniek** [comment]
I created Standard Event Hub namespace and I am getting `TopicAuthorizationException` from `spring-cloud-stream-binder-kafka`.  I created topic/Event Hub by myself, disabled `autoCreateTopics` and I cannot send any messages to Event Hub.

I am using `spring-cloud-stream` in 2.1.0.RC1 version.

Do you have any idea why is it not possible for me to auth to topic?

**Comment by czyzniek** [comment]
All right I resolved this issue. It looks like `spring-cloud-stream` must be in `2.0.2.RELEASE` version together with `spring-boot` in `2.0.7.RELEASE` version. With this combination everything seems to work fine.
