### ISSUE TITLE
EventHub Connection Failure

### ISSUE THREAD

**Issue by dgonza11** [Azure/azure-event-hubs-for-kafka#161]
Description
===========
My customer is trying to connect to EventHub however is receiving the following error:

ERROR: Could not connect to broker via tcp: <namespace>.servicebus.windows.net:9093
ERROR: Connection timed out
no valid broker connections established 

How to reproduce
================
Using following config file to connect:

Configuration
- topic = the Event Hub Instance Name
- properties = use the following for Shared Access Key authentication
bootstrap.servers={EVENT HUB NAMESPACE}.servicebus.windows.net:9093
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="{CONNECTION STRING for EVENT HUB 
NAMESPACE}";

Has it worked previously?
=========================
This a first attempt at getting the sample application to run. 

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed or where adequate information has not been provided.

Please provide the relevant information for the following items:
 - [ ] SDK (include version info): `<REPLACE with e.g., kafka-python/Java SDK/confluent-kafka-dotnet with version info>`
 - [ ] Sample you're having trouble with: `<REPLACE with e.g., Java quickstart>`
 - [x] If using Apache Kafka Java clients or a framework that uses Apache Kafka Java clients, version: `<REPLACE with e.g., 1.1.0>`
 - [ ] Kafka client configuration: `<REPLACE with e.g., auto.reset.offset=earliest, ..>` (*do not include your connection string or SAS Key*)
 - [ ] Namespace and EventHub/topic name
 - [ ] Consumer or producer failure `<REPLACE with e.g., Consumer failure>`
 - [ ] Timestamps *in UTC* `<REPLACE with e.g., Nov 7 2018 - 17:15:01 UTC>`
 - [ ] group.id or client.id `<REPLACE with e.g., group.id=cg-name>`
 - [ ] Logs provided (with debug-level logging enabled if possible, e.g. log4j.rootLogger=DEBUG) or exception call stack
 - [ ] Standalone repro `<REPLACE with e.g., Willing/able to send scenario to repro issue>`
 - [ ] Operating system: `<REPLACE with e.g., Ubuntu 16.04.5 (x64) LTS>`
 - [ ] Critical issue

If this is a question on basic functionality, please verify the following:
 - [ ] Port 9093 should not be blocked by firewall ("broker cannot be found" errors)
 - [x ] Pinging FQDN should return cluster DNS resolution (e.g. `$ ping namespace.servicebus.windows.net` returns ~ `ns-eh2-prod-am3-516.cloudapp.net [13.69.64.0]`)
 - [x ] Namespace should be either Standard or Dedicated tier, not Basic (TopicAuthorization errors)

**Comment by serkantkaraca** [comment]
Connection time-out sounds like a networking issue. You can check the firewall settings and make sure port 9093 is enabled for outbound traffic.

**Comment by dgonza11** [comment]
Customer created a private endpoint which solved the issue.
