### ISSUE TITLE
Running quickstart java sample thrown TimeoutException

### ISSUE THREAD

**Issue by warrenzhu25** [Azure/azure-event-hubs-for-kafka#19]
I used event hub kafka well, but recently always failed to connect. Running quickstart java sample throw such exception:

```java
org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
```

**Comment by warrenzhu25** [comment]
namespace is `spring-cloud-azure` and event hub is `eventhub1`.

**Comment by basilhariri** [comment]
Hi Warren, I'll need more information to help you. I've made an issues template for future issues, but for now could you provide the following information?


How to reproduce
============
<How to reproduce the issue, or remove section if not relevant>

First attempt?
=========
<Is this a first attempt at getting the sample application to run, or did it work in the past and recently stop?>

Checklist
=========

 - [x] Apache Kafka version: `<REPLACE with e.g., 1.1.0>`
 - [ ] Kafka client configuration: `<REPLACE with e.g., auto.reset.offset=earliest, ..>` (*do not include your connection string or SAS Key*)
 - [ ] Namespace and EventHub/topic name
 - [ ] Consumer or producer failure `<REPLACE with e.g., Consumer failure>`
 - [ ] If consumer, partition ID, group ID `<REPLACE with e.g., partitionID=3, groupID=consumer-group>`
 - [ ] Timestamp in UTC `<REPLACE wtih e.g., Nov 7 2018 - 17:15:01 UTC> 
 - [ ] Client ID `<REPLACE with e.g., client ID = kafka-client>
 - [ ] Provide all logs (with debugging enabled if possible) or exception call stack
 - [ ] Standalone repro <REPLACE with e.g., Willing/able to send scenario to repro issue>
 - [ ] Operating system: `<REPLACE with e.g., Ubuntu 16.04.5 (x64) LTS>`
 - [ ] Critical issue

**Comment by basilhariri** [comment]
Okay, I just confirmed this sample still works with an Event Hub on my namespace. 

My thoughts:
* Have you made sure 9093 isn't being blocked by your firewall?
* Create a different Event Hub in your namespace (in the portal) then try again

**Comment by basilhariri** [comment]
For any future readers: The issue was the the namespace was not Kafka-enabled. This can be avoided by making sure you create your namespace using [this tutorial](https://docs.microsoft.com/azure/event-hubs/event-hubs-create-kafka-enabled).

**Comment by warrenzhu25** [comment]
Is there somewhere in the portal show whether kafka is enabled?

**Comment by basilhariri** [comment]
If the namespace is Kafka-enabled, the "Kafka Surface" field says ENABLED in the namespace overview page!

![image](https://user-images.githubusercontent.com/8660137/48922831-3185f800-ee5e-11e8-8494-b053a606054e.png)
