### ISSUE TITLE
Invalid session timeout

### ISSUE THREAD

**Issue by shinjisakaru** [Azure/azure-event-hubs-for-kafka#22]
Description
===========
I'm successful in sending messages to the event hub, but each time I try to initialize the receiver, I get this invalid session timeout error.

`2018-11-14 19:10:52.967|ssarkar#consumer-1|SEND| [thrd:sasl_ssl://ssarkar-test.servicebus.windows.net:9093/bootstrap]: sasl_ssl://ssarkar-test.servicebus.windows.net:9093/0: Sent JoinGroupRequest (v0, 109 bytes @ 0, CorrId 6)
2018-11-14 19:10:52.992|ssarkar#consumer-1|RECV| [thrd:sasl_ssl://ssarkar-test.servicebus.windows.net:9093/bootstrap]: sasl_ssl://ssarkar-test.servicebus.windows.net:9093/0: Received JoinGroupResponse (v0, 16 bytes, CorrId 6, rtt 24.28ms)
2018-11-14 19:10:52.992|ssarkar#consumer-1|REQERR| [thrd:main]: sasl_ssl://ssarkar-test.servicebus.windows.net:9093/0: JoinGroupRequest failed: Broker: Invalid session timeout: actions Permanent`

The only timeout I am specifying is the `request.timeout.ms`, and I have tried without that as well, but the error won't go away. I have also tried using various values of `session.timeout.ms` and still the error persists.

Has it worked previously?
=========================
Never worked

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:
 
 - [X] Verified that port 9093 is not blocked by firewall
 - [x] Verified the namespace is either Standard or Dedicated tier (i.e. it is not Basic tier, which isn't supported)
 - [x] Sample you're having trouble with: `dotnet quickstart`
 - [X] Apache Kafka version: `don't know`
 - [X] Full Kafka client configuration: `bootstrap.servers=<EVENT HUB FQDN>,
                    security.protocol=SASL_SSL,
                    sasl.mechanism=PLAIN,
                    sasl.username=$ConnectionString,
                    sasl.password=<CONNECTION STRING>,
                    ssl.ca.location=.\cacert.pem,
                    group.id=$Default,` (*do not include your connection string or SAS Key*)
 - [X] Namespace and EventHub/topic name: `ssarkar-test`
 - [X] Consumer failure 
 - [X] Provide all logs (with debugging enabled if possible) or exception call stack
 - [X] Timestamp in UTC `Nov 15 2018 - 20:15:01 UTC`

**Comment by basilhariri** [comment]
Hi @shinjisakaru please fill out the issues template checklist so we can have the information needed to help you. I've added and partially filled it out in your original comment for your convenience.

**Comment by shinjisakaru** [comment]
Thanks. Updated the checklist
