### ISSUE TITLE
Node Example is unclear

### ISSUE THREAD

**Issue by guysegal** [Azure/azure-event-hubs-for-kafka#23]
I'm trying to run the node quickstart example and it is unclear what is `$ConnectionString` and what is `{YOUR.EVENTHUB.CONNECTION.STRING}`

I assumed that `YOUR.EVENTHUB.CONNECTION.STRING` is the EventHub namespace connection string, and that `$ConnectionString` is the topic connection string, but it doesn't work.
What am I doing wrong?

**Comment by JamesBirdsall** [comment]
$ConnectionString is a literal. Do not change it.
