### ISSUE TITLE
Links in tutorial for spring-boot readme return 404

### ISSUE THREAD

**Issue by anno1985** [Azure/azure-event-hubs-for-kafka#233]
Description
===========
Links on the [Using Spring Boot with Azure Event Hubs for Apache Kafka Ecosystems](https://github.com/Azure/azure-event-hubs-for-kafka/tree/master/tutorials/spring-boot) page return 404. (This repo is linked from https://learn.microsoft.com/en-us/azure/event-hubs/event-hubs-exchange-events-different-protocols#next-steps and is supposed to contain examples.)

How to reproduce
================
Open page, click on either link.

Has it worked previously?
=========================
Probably, but the target repo was [reorganised](https://github.com/Azure/azure-docs-sdk-java/commit/d3b36331335a0d804f54f436254b69dc6b21c819).

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed or where adequate information has not been provided.

Please provide the relevant information for the following items:
 - [x] SDK (include version info): `n/a`
 - [x] Sample you're having trouble with: `cf. above`
 - [x] If using Apache Kafka Java clients or a framework that uses Apache Kafka Java clients, version: `n/a`
 - [x] Kafka client configuration: `n/a` (*do not include your connection string or SAS Key*)
 - [x] Namespace and EventHub/topic name
 - [x] Consumer or producer failure `n/a`
 - [x] Timestamps *in UTC* `n/a`
 - [x] group.id or client.id `n/a`
 - [x] Logs provided (with debug-level logging enabled if possible, e.g. log4j.rootLogger=DEBUG) or exception call stack: n/a
 - [x] Standalone repro `n/a`
 - [x] Operating system: `n/a`
 - [ ] Critical issue

If this is a question on basic functionality, please verify the following:
 - [x] Port 9093 should not be blocked by firewall ("broker cannot be found" errors): `n/a` 
 - [x] Pinging FQDN should return cluster DNS resolution (e.g. `$ ping namespace.servicebus.windows.net` returns ~ `ns-eh2-prod-am3-516.cloudapp.net [13.69.64.0]`): `n/a`
 - [x] Namespace should be either Standard or Dedicated tier, not Basic (TopicAuthorization errors): `n/a`

**Comment by hmlam** [comment]
documentation is updated to point to https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub.md
