### ISSUE TITLE
Example how to connect using PySpark (from Databricks)

### ISSUE THREAD

**Issue by sebader** [Azure/azure-event-hubs-for-kafka#26]
I'm trying to write data into an Kafka-enabled Event Hub from Azure Databricks using pyspark. I'm building on the [Scala sample ](https://github.com/Azure/azure-event-hubs-for-kafka/blob/master/tutorials/spark/sparkProducer.scala)but it always fails with 
`org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 273.0 failed 4 times, most recent failure: Lost task 0.3 in stage 273.0 (TID 174897, 10.139.64.8, executor 3): kafkashaded.org.apache.kafka.common.KafkaException: Failed to construct kafka producer`

Using the following code:

> EH_SASL = "kafkashaded.org.apache.kafka.common.security.plain.PlainLoginModule required username=\"$ConnectionString\" password=\"Endpoint=sb://xxxx.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=********************=\";"
> 
> dfKafka \
>     .write  \
>     .format("kafka") \
>     .option("kafka.sasl.mechanism", "PLAIN") \
>     .option("kafka.security.protocol", "SASL_SSL") \
>     .option("kafka.sasl.jaas.config", EH_SASL) \
>     .option("kafka.bootstrap.servers", "*****.servicebus.windows.net:9093") \
>     .option("topic", "vwraw") \
>     .option("checkpointLocation", "///write_kafka_parquet.txt") \
>     .save()

spark-sql-kafka-0-10_2.11-2.4.0
Databricks 4.3 (includes Apache Spark 2.3.1, Scala 2.11)

What am I missing? Thanks for any help!

**Comment by arerlend** [comment]
Just curious, what is this?

EH_SASL = "**kafkashaded**.org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://xxxx.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=********************=";"

"_Failed to construct kafka producer_" is just a umbrella error for when a client is configured incorrectly (could be any number of things).

**Comment by sebader** [comment]
https://github.com/Azure/azure-event-hubs-for-kafka/tree/master/tutorials/spark#running-spark

> Note: Databricks shades the Kafka client under the kafkashaded package. If you are using Databricks to run Spark, make sure to update all occurrences of org.apache.kafka.common.security.plain.PlainLoginModule to kafkashaded.org.apache.kafka.common.security.plain.PlainLoginModule in these samples!

But I tried all kinds of different variants - so also the original org.apache.kafka... as well as the kafkashaded. Any many other versions I could think of.

**Comment by arerlend** [comment]
Got it.  Someone on the team has been testing Spark but as far as I know we haven't tried out pyspark.  I'll give him a heads up.

**Comment by basilhariri** [comment]
Hi @sebader 

That Databricks runtime version (4.3) uses Spark v2.3 included which isn't supported. I'm pretty sure Databricks is ignoring your `spark-sql-kafka-0-10_2.11-2.4.0` entirely because that library is already included in the runtime. 

Try again with Databricks runtime version 5.0+ and let us know if that doesn't solve the issue.

**Comment by sebader** [comment]
ok, I'll try that. But is my command above in general correct or how should this look like in DB 5.0?

**Comment by basilhariri** [comment]
There were no major changes to Spark queries in this release, so I wouldn't expect any issues if this query has worked for you in the past.

**Comment by sebader** [comment]
So, I got the query to run (never had it working before anywhere, so took some time to figure it out).

```
EH_SASL = 'kafkashaded.org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://myeh.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=****************";'

dfKafka \
    .write  \
    .format("kafka") \
    .option("kafka.sasl.mechanism", "PLAIN") \
    .option("kafka.security.protocol", "SASL_SSL") \
    .option("kafka.sasl.jaas.config", EH_SASL) \
    .option("kafka.bootstrap.servers", "myeh.servicebus.windows.net:9093") \
    .option("topic", "topicX") \
    .option("checkpointLocation", "///checkpoint.txt") \
    .save()
```


It started up and sent a couple of million rows to the EventHub. But my DataFrame had about 230 million records and after a few minutes the command just stopped with

> org.apache.spark.SparkException: Job aborted due to stage failure: Task 5 in stage 11.0 failed 4 times, most recent failure: Lost task 5.3 in stage 11.0 (TID 359, 10.139.64.5, executor 2): kafkashaded.org.apache.kafka.common.errors.TimeoutException: Expiring 64 record(s) for vwraw-18: 30090 ms has passed since batch creation plus linger time

any idea for this one?

**Comment by basilhariri** [comment]
Unless it works with a standard Kafka cluster but fails when you switch over to EventHubs for Kafka, I would guess this is just a Spark tuning issue.

**Comment by sebader** [comment]
Yeah didn't have time yet to also test that against a regular Kafka cluster. Was hoping you might have some experience and a quick idea ;-)

**Comment by sebader** [comment]
Ok, got it to work now with a smaller batch.size parameter:

``` dfKafka \
.write  \
.format("kafka") \
.option("kafka.sasl.mechanism", "PLAIN") \
.option("kafka.security.protocol", "SASL_SSL") \
.option("kafka.sasl.jaas.config", EH_SASL) \
.option("kafka.batch.size", 5000) \
.option("kafka.bootstrap.servers", "myeventhub.servicebus.windows.net:9093") \
.option("kafka.request.timeout.ms", 120000) \
.option("topic", "raw") \
.option("checkpointLocation", "/mnt/telemetry/cp.txt") \
.save()```

Turns out this really seems to be a much faster alternative for writing data to an Even Hub from Databricks than using the EventHub connector. Got to about 700k messages per minute using Kafka protocol.
