### ISSUE TITLE
Last Kafka consumer in a concurrent consumers scenario crashes during the election process

### ISSUE THREAD

**Issue by archetec** [Azure/azure-event-hubs-for-kafka#27]
Description
===========
As a test we launch 2 Kafka consumers (using Confluent .Net client component v0.11.6) on the same topic and in the same consumer group…  The topic has a single partition, so the 2 consumers are competing and only one is getting assigned to the partition.  Everything is ok.  Then we shut down (or kill) one of them. The second one enters in the re-balance process but then crashes, and it’s not a clean crash.   I can’t even get a stack trace, only a Windows 7 dialog box that says the program crashed (it’s a .Net console program).  I was surprised by this behavior so I tried with a Kafka broker (same code, just changed the connection parameters), and the consumer does re-balance properly without crashing.

How to reproduce
================

1. Launch 2 Kafka consumers on the same topic (with only one partition) and using the same consumer group.
2. Stop (kill) one of them.
3. Watch the other one crash.

(This issue was reported to the Event Hub team on 29/11 and I also provided a code sample.)

Tried with different versions on .Net from 4.5.2 to 4.7.2 and on Win7 and Win10.

Has it worked previously?
=========================
I never tried this scenario before the GA.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:
 
 - [X] Verified that port 9093 is not blocked by firewall
 - [X] Verified the namespace is either Standard or Dedicated tier (i.e. it is not Basic tier, which isn't supported)
 - [x] Sample you're having trouble with: `<REPLACE with e.g., Java quickstart>`
 - [x] Apache Kafka version: `<REPLACE with e.g., 1.1.0>`
 - [x] Kafka client configuration: `<REPLACE with e.g., auto.reset.offset=earliest, ..>` (*do not include your connection string or SAS Key*)
 - [x] Namespace and EventHub/topic name
 - [x] Consumer or producer failure `<REPLACE with e.g., Consumer failure>`
 - [ ] If consumer, partition ID, group ID `<REPLACE with e.g., partitionID=3, groupID=consumer-group>`
 - [ ] Timestamp in UTC `<REPLACE wtih e.g., Nov 7 2018 - 17:15:01 UTC> 
 - [ ] Client ID `<REPLACE with e.g., clientID=kafka-client>
 - [X] Provide all logs (with debugging enabled if possible) or exception call stack
 - [X] Standalone repro <REPLACE with e.g., Willing/able to send scenario to repro issue>
 - [X] Operating system: `<REPLACE with e.g., Ubuntu 16.04.5 (x64) LTS>`
 - [ ] Critical issue

**Comment by arerlend** [comment]
Hey Eric - thanks for opening the issue.  We're passing back a message that causes a parse exception due to an empty field.  Working on a fix to be released ASAP.  I'll keep this thread updated.

**Comment by arerlend** [comment]
A fix is checked in in our hotfix branch.  I'll close this issue once deployed.

**Comment by archetec** [comment]
Thanks for the follow up Arthur.  I'll do a quick test on our side once it's available in Canada East, although I'm sure it'll be just fine.

**Comment by arerlend** [comment]
Fix is deployed.
