### ISSUE TITLE
Unable to produce topic on eventhub

### ISSUE THREAD

**Issue by mojari** [Azure/azure-event-hubs-for-kafka#29]
I have downloaded the java producer and consumer:
https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/event-hubs/event-hubs-quickstart-kafka-enabled-event-hubs.md

I have create event-hub namespace on event hub and modified the producer.conf like:
bootstrap.servers=eventhubXXXX.servicebus.windows.net:9093
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" \
password="Endpoint=sb://eventhubXXXXX.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=*******************";

When I am executing  mvn exec:java -Dexec.mainClass="TestProducer"

then getting following error:
Test Data #95 from thread #13
Test Data #96 from thread #13
Test Data #97 from thread #13
Test Data #98 from thread #13
Test Data #99 from thread #13
Finished sending 100 messages from thread #13!
org.apache.kafka.common.errors.TopicAuthorizationException: Not authorized to access topics: [test]

**Comment by tpanagos** [comment]
Similar problem running the Scala tutorial. Consumer reports errors below. Producer does not report error msg but does not create messages. 

[ERROR] [12/21/2018 10:49:27.789] [akka-stream-kafka-akka.kafka.default-dispatcher-8] [akka://akka-stream-kafka/system/kafka-consumer-1] Exception when polling from consumer
org.apache.kafka.common.errors.TopicAuthorizationException: Not authorized to access topics: [create-json]

Tried both root SAS key and sub-key settings in the application.conf:
sasl.jaas.config="org.apache.kafka.common.security.plain.PlainLoginModule required username=\"$ConnectionString\" password=\"Endpoint=sb://foobar.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=somekeystuffhere=\";"

sasl.jaas.config="org.apache.kafka.common.security.plain.PlainLoginModule required username=\"$ConnectionString\" password=\"Endpoint=sb://foobar.servicebus.windows.net/;SharedAccessKeyName=myservicename-service;SharedAccessKey=someotherkeystuffs=;EntityPath=create-json\";"

**Comment by tpanagos** [comment]
@mojari Do you have the event hub (aka topic) called "test" defined in your event hub namespace in Azure?

**Comment by mojari** [comment]
This time, I have created topic first. Still, I am getting same error:

[devlab_user@dl-mstr2 producer]$ mvn exec:java -Dexec.mainClass="TestProducer"
[INFO] Scanning for projects...
[INFO]
[INFO] -----------< com.example.app:event-hubs-kafka-java-producer >-----------
[INFO] Building event-hubs-kafka-java-producer 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ event-hubs-kafka-java-producer ---
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Test Data #0 from thread #13
org.apache.kafka.common.errors.TopicAuthorizationException: Not authorized to access topics: [test2]

I have not modified This "$ConnectionString" username value worries me..

We have to give any specific value here?

**Comment by tpanagos** [comment]
@mojari I did get my connection to work. I am not sure what the difference is yet. 

1. I created a new namespace without a dash (my first one had a dash in it
2. Made sure to select the kafka enabled box on the namespace 
3. Created the new resource in US East 1
4. I updated the sasl.jaas.config with the new RootManageSharedAccessKey string, I left $ConnectionString
5. I did not manually create the event hub (topic)
5. recompiled and ran

Works! Producer and Consumer

sasl.jaas.config="org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://foobar.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=somekeystuffhere=";"

I am not positive which of these made the difference. I will continue to debug.

**Comment by mojari** [comment]
Thanks. Even, I am not sure, what is causing issue? As, I can see, if I am running the producer with different topic name(new another topic name), I can see in azure, new topic(event hub) is getting created, But, I am getting the same error at producer side. Not authorized to access topics: [test2]

**Comment by basilhariri** [comment]
@mojari 

Usually when you hit a topic unauthorized error it can be one of a few things which are listed [here](https://github.com/Azure/azure-event-hubs-for-kafka#other-issues) under TopicAuthorizationException

Based on what you've provided already, I noticed the config file you posted has a new line between the sasl.jaas.config and the password. This is incorrect, the password is part of the sasl.jass.config which should look something like this:

sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://eventhubXXXXX.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey={YOUR.CONNECTION.STRING}";

If you copy that and replace {YOUR.CONNECTION.STRING} with your actual connection string, and eventhubXXXXXX with your actual namespace name, I think it'll work.

PS: I removed your SAS key from your comment and deleted it from the comment history. Please make sure not to post your SAS key on public forums. Even if this EventHub isn't particularly important, SAS keys are secrets so please make sure not to include them in future issues!

**Comment by mojari** [comment]
Thanks. Closing this issue.
