### ISSUE TITLE
Spark Struct data lost when serialized as Avro

### ISSUE THREAD

**Issue by james-tn** [Azure/azure-event-hubs-for-kafka#33]
Description
===========
When serializing data into Avro format by using Spark Streaming  (Databricks) on struct data and use EventHub Kafka, the Struct data lost some field value
<Describe the issue here>

How to reproduce
================
<How to reproduce the issue, or remove section if not relevant>
1. Using Azure Databricks to create a streaming dataframe (Structured Streaming)
2. Use to_avro function to serialize a struct field (struct in Scala that has multiple fields) into avro
3. Write to a Kafka topic as value
4. Use Databricks to read from the same topic
5. Use to_avro function with the same schema used to serialize data. Just some of the fields have value. Other fields does not have value
The to_avro and from_avro worked in other Kafka platforms
Has it worked previously?
No
=========================
<Is this a first attempt at getting the sample application to run, or has it worked in the past?>

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:
 
 - [x] Verified that port 9093 is not blocked by firewall
yes
 - [x] Verified the namespace is either Standard or Dedicated tier (i.e. it is not Basic tier, which isn't supported)
yes
 - [ ] Sample you're having trouble with: `<REPLACE with e.g., Java quickstart>`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 1.1.0>`
 - [x] Kafka client configuration: `<REPLACE with e.g., auto.reset.offset=earliest, ..>` (*do not include your connection string or SAS Key*)
    .format("kafka")
    .option("topic", TOPIC)
    .option("kafka.bootstrap.servers", BOOTSTRAP_SERVERS)
    .option("kafka.sasl.mechanism", "PLAIN")
    .option("kafka.security.protocol", "SASL_SSL")
    .option("kafka.sasl.jaas.config", EH_SASL)
    .option("checkpointLocation", "dbfs:/mnt/cp/cp36")

 - [x] Namespace and EventHub/topic name
kafkaeventhub01/kafka_spark
 - [x] Consumer or producer failure `<REPLACE with e.g., Consumer failure>`
none of them failed, just data lost
 - [x] If consumer, partition ID, group ID `<REPLACE with e.g., partitionID=3, groupID=consumer-group>`
GROUP_ID = "$Default"

 - [ ] Timestamp in UTC `<REPLACE wtih e.g., Nov 7 2018 - 17:15:01 UTC>`
 - [ ] Client ID `<REPLACE with e.g., clientID=kafka-client>`
 - [ ] Provide all logs (with debugging enabled if possible) or exception call stack

 - [x] Standalone repro `<REPLACE with e.g., Willing/able to send scenario to repro issue>`
Willing
 - [x] Operating system: `<REPLACE with e.g., Ubuntu 16.04.5 (x64) LTS>`
Databricks
 - [ ] Critical issue

**Comment by basilhariri** [comment]
Sent mail. Will post any updates as we have them.

**Comment by basilhariri** [comment]
The issue was that the messages were encoded using Confluent's library, and were not being decoded with the same library.
