### ISSUE TITLE
Unable to run Python producer/consumer example due to SSL issue

### ISSUE THREAD

**Issue by margaretmeehan** [Azure/azure-event-hubs-for-kafka#36]
Description
===========
When I run `python producer.py topic_name` after running the setup script, I get 

```
Traceback (most recent call last):
  File "producer.py", line 33, in <module>
    p = Producer(**conf)
cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="Invalid value "SASL_SSL" for configuration property "security.protocol""}
```

I have openssl installed.

How to reproduce
================
I ran the setup script and updated the config as instructed. I.E. I updated the sasl.password with my EH Namespace Connection String, and set the bootstrap.server to my FQDN (i.e. {EH_NAMESPACE_NAME}.servicebus.windows.net:9093). 

After I got the SASL_SSL error, I went into the Producer.py code and saw the link to create a ca-certificate and set ssl.ca.location. So I followed the instructions [here](https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka#prerequisites) and created a certificate using the command `gen-ssl-certs.sh ca ca-cert test`.  But I still got the same error that SASL_SSL is invalid after updating the ssl.ca.location field. 

Has it worked previously?
=========================
No.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:
 
 - [x] Verified that port 9093 is not blocked by firewall
 - [x] Verified the namespace is either Standard or Dedicated tier (i.e. it is not Basic tier, which isn't supported)
 - [x] Sample you're having trouble with: `Python quickstart>`
 - [x] Apache Kafka version: `https://github.com/edenhill/librdkafka>`
 - [X] Kafka client configuration: `conf = {
        'bootstrap.servers': '{YOUR.EVENTHUBS.FQDN}:9093',
        'security.protocol': 'SASL_SSL',
        'ssl.ca.location': '/path/to/ca-certificate.crt',
        'sasl.mechanism': 'PLAIN',
        'sasl.username': '$ConnectionString',
        'sasl.password': '{YOUR.EVENTHUBS.CONNECTION.STRING}',
        'client.id': 'python-example-producer'
    }`
 - [x] Namespace and EventHub/topic name `namespace: kafka-eh-demo, topic: input-eh`
 - [X] Consumer or producer failure `Producer failure`
 - [X] If consumer, partition ID, group ID `<REPLACE with e.g., partitionID=3, groupID=consumer-group>`
 - [X] Timestamp in UTC `Thu, 31 Jan 2019 20:10:04`
 - [X] Client ID `python-example-producer`
 - [X] Provide all logs (with debugging enabled if possible) or exception call stack
 - [X] Standalone repro `<Willing/able to send scenario to repro issue>`
 - [X] Operating system: `macOS 10.13.6`
 - [X] Critical issue

**Comment by arerlend** [comment]
Looks fine to me.  I'll do some testing on MacOS later.

**Comment by margaretmeehan** [comment]
Closed! Thank you @arerlend. Ensure openssl is installed correctly for Mac OS users and set your ssl.ca.location to the openssl certificate location
