### ISSUE TITLE
org.apache.kafka.common.protocol.types.SchemaException When re-balancing

### ISSUE THREAD

**Issue by hope4555** [Azure/azure-event-hubs-for-kafka#41]
Description
===========
We use Azure event hubs (Kafka style)

We are getting this exception:
org.apache.kafka.common.protocol.types.SchemaException
when Kafka is re-balancing the consumers in a consumer group

How to reproduce
================
Scenario:
1. Connect first consumer - it will get 32 partitions.
2. Connect second consumer to the same group - re-balance will happen.
3. The first consumer will "free" 16 partitions and will have now 16 partitions.
4. New consumer will get 16 partitions.

now:
5. Close the second consumer.
6. First consumer, instead of getting back all 32 partitions , will throw "SchemaException"

Has it worked previously?
=========================
No

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.
Please provide the following information:
 
 - [x] Verified that port 9093 is not blocked by firewall
 - [x] Verified the namespace is either Standard or Dedicated tier (i.e. it is not Basic tier, which isn't supported)
 - [ ] Sample you're having trouble with: `Java`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 1.1.1>`
 - [ ] Kafka client configuration: `<REPLACE with e.g., auto.reset.offset=earliest, ..>` 
 - [ ] Namespace and EventHub/topic name
 - [x] Consumer or producer failure `Consumer failure`
 - [ ] If consumer, partition ID, group ID `<REPLACE with e.g., partitionID=3, groupID=consumer-group>`
 - [ ] Timestamp in UTC `<REPLACE wtih e.g., Nov 7 2018 - 17:15:01 UTC>`
 - [ ] Client ID `<REPLACE with e.g., clientID=kafka-client>`
 - [x] Provide all logs (with debugging enabled if possible) or exception call stack
 - [x] Standalone repro `<REPLACE with e.g., Willing/able to send scenario to repro issue>`
 - [ ] Operating system: `<REPLACE with e.g., Ubuntu 16.04.5 (x64) LTS>`
 - [ ] Critical issue

**Stack Trace** 
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'leader_id': String length -1 cannot be negative
Schema Exception Error: Error reading field 'leader_id': String length -1 cannot be negative
	at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:77)
	at org.apache.kafka.common.protocol.ApiKeys.parseResponse(ApiKeys.java:294)
	at org.apache.kafka.clients.NetworkClient.parseStructMaybeUpdateThrottleTimeMetrics(NetworkClient.java:586)
	at org.apache.kafka.clients.NetworkClient.handleCompletedReceives(NetworkClient.java:686)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:469)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:261)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:193)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:364)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:316)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:290)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1149)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1115)
	at com.bgprotect.eventhub.CheckRevoke.main(CheckRevoke.java:51)

**Example Code:**

package com.bgprotect.eventhub;

import java.util.Collection;
import java.util.Collections;
import java.util.Properties;
import java.util.UUID;

import org.apache.kafka.clients.CommonClientConfigs;
import org.apache.kafka.clients.consumer.Consumer;
import org.apache.kafka.clients.consumer.ConsumerConfig;
import org.apache.kafka.clients.consumer.ConsumerRebalanceListener;
import org.apache.kafka.clients.consumer.ConsumerRecord;
import org.apache.kafka.clients.consumer.ConsumerRecords;
import org.apache.kafka.clients.consumer.KafkaConsumer;
import org.apache.kafka.common.TopicPartition;
import org.apache.kafka.common.config.SaslConfigs;
import org.apache.kafka.common.protocol.types.SchemaException;
import org.apache.kafka.common.serialization.LongDeserializer;

import com.bgprotect.bgmessages2.BackendMessages.BusResultMessage;
import com.bgprotect.eventhub.util.MeasurementDeSerializer;

public class CheckRevoke {
	private static class SaveOffsetsOnRebalance implements ConsumerRebalanceListener {
		@Override
		public void onPartitionsRevoked(Collection<TopicPartition> parts) {
			System.out.println("onPartitionsRevoked " + parts);
		}
		
		@Override
		public void onPartitionsAssigned(Collection<TopicPartition> parts) {
			System.out.println("onPartitionsAssigned " + parts);
		}
	}
	
	public static void main(String[] args) {
		SaveOffsetsOnRebalance saveOffsetsOnRebalance = new SaveOffsetsOnRebalance();
		
		String sasKey = "<sas key>";
		String groupName = "<group name>";
		String namespace = "<namespace>";
		String topic = "<topic>";
		
		String connectionString = String.format("Endpoint=sb://%s.servicebus.windows.net/;SharedAccessKeyName=%s;SharedAccessKey=%s;EntityPath=%s", namespace,
				"RootManageSharedAccessKey", sasKey, topic);
		
		try (Consumer<Long, BusResultMessage> consumer = createMeasurementConsumer("cp-" + UUID.randomUUID().toString(), saveOffsetsOnRebalance,
				connectionString, groupName, namespace, topic)) {
			while (true) {
				try {
					final ConsumerRecords<Long, BusResultMessage> consumerRecords = consumer.poll(10000);
					for (ConsumerRecord<Long, BusResultMessage> cr : consumerRecords) {
						System.out.print(cr.partition());
					}
					System.out.println();
					Thread.sleep(8000);
				} catch (SchemaException e) {
					e.printStackTrace();
					System.out.println("Schema Exception Error: " + e.getMessage());
					break;
				} catch (Exception e) {
					e.printStackTrace();
					break;
				}
			}
		}
		
	}
	
	public static Consumer<Long, BusResultMessage> createMeasurementConsumer(String clientId, ConsumerRebalanceListener listener, String password,
			String groupName, String namespace, String topic) {
		String saslJaasConfig = String.format("org.apache.kafka.common.security.plain.PlainLoginModule required username=\"$ConnectionString\"password=\"%s\";",
				password);
		Properties properties = new Properties();
		properties.put(SaslConfigs.SASL_MECHANISM, "PLAIN");
		properties.put(SaslConfigs.SASL_JAAS_CONFIG, saslJaasConfig);
		properties.put(CommonClientConfigs.SECURITY_PROTOCOL_CONFIG, "SASL_SSL");
		properties.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, String.format("%s.servicebus.windows.net:9093", namespace));
		properties.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, LongDeserializer.class.getName());
		properties.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, MeasurementDeSerializer.class.getName());
		properties.put(ConsumerConfig.MAX_POLL_INTERVAL_MS_CONFIG, 60000);
		properties.put(ConsumerConfig.GROUP_ID_CONFIG, groupName);
		properties.put(ConsumerConfig.CLIENT_ID_CONFIG, clientId);
		
		final Consumer<Long, BusResultMessage> consumer = new KafkaConsumer<>(properties);
		consumer.subscribe(Collections.singletonList(topic), listener);
		return consumer;
	}
}

**Comment by arerlend** [comment]
This should have been fixed previously.  Thanks for the repro steps, will get back by tomorrow.

**Comment by arerlend** [comment]
@hope4555 is the closed consumer being closed using `consumer.close()` or is it being killed?

**Comment by hope4555** [comment]
You mean the consumer on the other PC?
If yes, then lets assume that the second PC gone dead, maybe disconnected from network or process killed
I can check on Sunday if the second PC is closed cleanly it still happens , but i think it really does not mapper if the send PC is closing the connection cleanly or not

**Comment by arerlend** [comment]
Yeah that's it.  The previous fix was for the clean LeaveGroup shutdown case.

I'll keep this thread updated on progress.

**Comment by hope4555** [comment]
Ok, thanks, check and truly when closing the connection cleanly there is no exception

**Comment by arerlend** [comment]
Yeah calling consumer.close() uses the LeaveGroup API which is running down a different code path in EH than the expired consumer's kick.

A fix is in the pipeline, I'll update when it's completed.

**Comment by rbrandt-r7** [comment]
Is there any update on this fix?

**Comment by paperMoose** [comment]
Any update here? I'm in a similar situation to hope4555

**Comment by arerlend** [comment]
We have a fix but it will need to go through stress testing.  It should be released in the next hotfix though.

**Comment by SaiChand-reddy** [comment]
Any update here? I'm in a similar situation to hope4555

**Comment by arerlend** [comment]
Hotfix deployment is in progress.  I'll update when deployment is completed.  Sorry about the wait, this will be resolved soon.

**Comment by arerlend** [comment]
Fix is hitting some clusters.  I'll close the issue for now, but if you have additional questions, feel free to reach out at arerlend@microsoft.com

**Comment by ponmanikandanb** [comment]
is this fixed?

**Comment by arerlend** [comment]
This issue has been fixed and the fix has been deployed.

**Comment by jestevez** [comment]
Hi, in which commit, version is this resolved?
