### ISSUE TITLE
Can Kafka connect internal  Topics ( event hub) be made as compact enabled

### ISSUE THREAD

**Issue by SaravananVT** [Azure/azure-event-hubs-for-kafka#42]
Description
===========
Kafka Connect internal topics where it stores configs , offsets and status.  Especially config topic is typically compact enabled where the configs are supplied one time through rest post and remains there forever. how can this be done in Azure Event Hub as we dont see compact option - our configs are expired out after the retention period set and  app couldnt start ( during any restart) as its not finding the config

**Comment by arerlend** [comment]
Just wanted to make sure you're aware that Connect support is still in preview.  A couple questions though -

1. Did you create the topics by hand? Or did you allow Connect to create the topics during its setup?  Connect creates topics explicitly w/ a compacted flag.  If you created by hand, the default EH retention period is set and your messages get expired and cleaned up.
2. If Connect created the topics, how long have you been running your Connect cluster?

**Comment by SaravananVT** [comment]
Thanks for the response. Yes am aware that connect is in preview. Wanted to check if this is handled in preview mode 
1. We created the topics manually before running the connect. 
2.Shall try  with connect creating it and share the feedback

**Comment by arerlend** [comment]
Sounds good.

You're probably aware, but for anybody reading this later, it's possible to specify partition count for Connect for those internal topics, even if you let Connect create them automatically - https://docs.confluent.io/current/connect/userguide.html#distributed-worker-configuration

**Comment by SaravananVT** [comment]
Thanks for the links. After letting the Connect to create internal topics - connect is started but it doesnt seems to run the connector tasks - I have doubt that if am using right ASE tiers ( I1 - Dv2 , 3.5GB , 210ACU ) so the connector gets right resources -  no apps running in the app service plan. Is there any specific requirement for connect to run.  .
Am using Confluent Kakfa Connect images and passing the variables as environment variables to docker through my release pipeline - Getting this ERROR - Failed to reconfigure connector tasks - retrying after backoff.  please help give some direction .

**Comment by arerlend** [comment]
There should be more to the error, please post the stack trace.  The error could be with the Connect process itself OR with your connector config, but there's no way for me to tell right now.

**Comment by SaravananVT** [comment]
We figured this problem to be that SSL configs are not supplied to Connector properly. All producer & consumer configs are expected to be prefix with CONNECT_.  After adding this , able to push messages successfully .
