### ISSUE TITLE
Losing messages when consumer is offline

### ISSUE THREAD

**Issue by rafaelvicio** [Azure/azure-event-hubs-for-kafka#44]
Description
===========

When you call an event producer with the consumer turned off, messages are lost.

When I start the consumer he does not read the messages sent beforehand.

How to reproduce
================

Call the producer
- Send 3 messages by the producer 
- Connect the consumer 
- He should read all 3 messages

**Comment by arerlend** [comment]
What offset are you starting the consumer with? Are you setting its offset to be earliest?

When a Kafka consumer starts and doesn't find an offset for its consumer group on a specific partition, it will default to the end of the partition, in this case, after the messages you sent.  So this is actually the desired behavior.

You should be able to see the messages if you start the consumer _then_ send the messages.

**Comment by arerlend** [comment]
https://stackoverflow.com/questions/32390265/what-determines-kafka-consumer-offset
