### ISSUE TITLE
Fails to commit offset for one particular partition

### ISSUE THREAD

**Issue by slavirok** [Azure/azure-event-hubs-for-kafka#46]
Description
===========
MirrorMaker has been running without issues for some time until one day(~a week ago) it started crashing and restarting every few minutes.
From its logs, we found out that it continuously fails to commit offset for the same partition (see logs below). This is causing MirrorMaker to ingest data from that partition multiple times.

Has it worked previously?
=========================
We didn't face this issue in the past.

Checklist
=========
 - [x] Verified that port 9093 is not blocked by firewall
 - [x] Verified the namespace is either Standard or Dedicated tier (i.e. it is not Basic tier, which isn't supported)
 - [x] Apache Kafka version: `kafka_2.12-2.1.0`
 - [x] Kafka client configuration: 
`bootstrap.servers=${EVENTHUB_BOOTSTRAP_SERVER}
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${DOLLAR}ConnectionString" password="${EVENTHUB_CONNECTION_STRING}";
group.id=${EVENTHUB_CLIENT_ID}
client.id=${EVENTHUB_CLIENT_ID}
exclude.internal.topics=true
partition.assignment.strategy=org.apache.kafka.clients.consumer.RoundRobinAssignor
sasl.mechanism=PLAIN
security.protocol=SASL_SSL
auto.offset.reset=earliest`
 - [x] Consumer or producer failure `Consumer`
 - [x] If consumer, partition ID, group ID `partitionID=15`
 - [x] Provide all logs (with debugging enabled if possible) or exception call stack
 - [x] Critical issue

Logs from MirroMaker:
[2019-04-15 09:30:36,803] ERROR [Consumer clientId=clientid-name-0, groupId=group_name] Offset commit failed on partition topic-name-15 at offset 486021: The server disconnected before a response was received. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)

[2019-04-15 09:23:16,677] ERROR [Consumer clientId=clientid-name-0, groupId=group_name] Offset commit failed on partition topic-name-15 at offset 485993: The server disconnected before a response was received. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)

[2019-04-15 09:15:55,137] ERROR [Consumer clientId=clientid-name-0, groupId=group_name] Offset commit failed on partition topic-name-15 at offset 485964: The server disconnected before a response was received. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)

**Comment by arerlend** [comment]
Sorry about this.  We already have a fix currently being deployed.

In the meantime, you can work around the issue by going to the Azure portal and changing the message retention period.  This will reload the affected Event Hubs and the error should go away.

**Comment by slavirok** [comment]
Hi @arerlend.
The workaround fixed the initial issue.
We are still getting quite a few warnings for all the partitions:
`Unknown error fetching data for topic-partition topicname-partitionumber`

**Comment by arerlend** [comment]
Update: confirmed that the fix being deployed resolves this issue.  Consumption should return to normal after applying the workaround listed above.  You can apply it as often as necessary.

I'll update the thread again when deployment is completed.

**Comment by arerlend** [comment]
Most of your clusters should be receiving the fix today.  I'm going to close this issue, but if you have questions, feel free to contact me directly at arerlend@microsoft.com
