### ISSUE TITLE
V1 SaslHandshake+SaslAuthenticate not working

### ISSUE THREAD

**Issue by evandigby** [Azure/azure-event-hubs-for-kafka#48]
Description
===========
[V1 SaslHandshake](https://kafka.apache.org/protocol.html#The_Messages_SaslHandshake) appears to be broken--as a result, no clients that attempt to use V1 (most native Go clients and a few other clients) can authenticate.

[Confluent Kafka Go](https://github.com/confluentinc/confluent-kafka-go) always seems to use V0, as do the Java clients, which is why they work.

I've got a [working auth flow](https://github.com/evandigby/kafka) and a [fix for Sarama](https://github.com/evandigby/sarama/commit/6509b6f9a616196089617e28f70ea2e21e8406ae):
- https://github.com/evandigby/kafka
- https://github.com/evandigby/sarama/commit/6509b6f9a616196089617e28f70ea2e21e8406ae

How to reproduce
================
Attempt to connect using [Sarama Kafka client](https://github.com/Shopify/sarama).

Has it worked previously?
=========================
Has not worked previously afaik.

Checklist
=========

Please provide the following information:
 
 - [x] Verified that port 9093 is not blocked by firewall
 - [x] Verified the namespace is either Standard or Dedicated tier (i.e. it is not Basic tier, which isn't supported)
 - [x] Sample you're having trouble with: [https://github.com/evandigby/kafka](https://github.com/evandigby/kafka)
 - [x] Apache Kafka version: `Azure Event Hubs for Kafka`
 - [x] Kafka client configuration: N/A
 - [x] Namespace and EventHub/topic name: `would prefer to keep this private but can provide if required`
 - [x] Consumer or producer failure `both--auth failure`
 - [x] If consumer, partition ID, group ID `N/A`
 - [x] Timestamp in UTC `attempts made around 2019-05-02 02:00 to 03:00-ish`
 - [x] Client ID `testClient`
 - [x] Provide all logs N/A
 - [x] Standalone repro `willing to send`
 - [x] Operating system: `Windows 10 and Ubuntu WSL (up-to-date)`
 - [x] Critical issue (critical with workaround)

**Comment by sjkwak** [comment]
Thanks for reporting the issue, @evandigby. SaslHandshake version 1 is currently not supported. We will update the service so that API version response doesn't include version 1 for the SaslHandshake API until v1 is fully supported.

**Comment by evandigby** [comment]
Thank you @sjkwak! 

FWIW there are a few other more minor issues with the ApiRequest response. For example it doesn’t report being compatible with SaslAuthenticate—just handshake. Doesn’t seem to trip up clients though.

I assume that means I’ll have to submit a PR for sarama to perform a more reliable check for ApiVersion (right now they do it based on the user-specified Kafka version) but that’s not on your team!

**Comment by sjkwak** [comment]
Hi @evandigby, the service doesn't support SaslAuthenticate API yet and hence the response of the ApiRequest call doesn't include the version info of the SaslAuthenticate API. We will add it once the service supports SaslHandshake v1.

**Comment by evandigby** [comment]
Hi @sjkwak there is a SaslAuthenticate V0 request in the spec that matches SaslHandshake V0. That represents the “opaque” (no Kafka headers) sasl authentication request. 

Since the kafka endpoint requires SaslAuthentication it should (and does) support V0 of SaslAuthenticate.

Thanks!

**Comment by sjkwak** [comment]
@evandigby, for SaslHandshakeRequest v0 case, a security context corresponding to the mechanism is sent separately and it is not part of SaslAuthenticate request. And, SaslAuthenticate request is used if SaslHandshakeRequest version is v1.

**Comment by evandigby** [comment]
@sjkwak ah you’re very right. I misread it! Apologies for the doubt. It’s been a long day staring at the docs figuring things out—words blurred together :)

Thanks for tour help!!

**Comment by OnurbHartmann** [comment]
Hello @sjkwak, have the issues been fixed on Azure Event hub?  Does the Event Hub now support SaslHandshake  V1? If not, is there are plan till when it will?
thx for help
