### ISSUE TITLE
PHP sample?

### ISSUE THREAD

**Issue by robert-schmidt** [Azure/azure-event-hubs-for-kafka#51]
Description
===========
Please provide some guidelines that would help PHP developers connecting and using Kafka Event Hubs. I'm feel like losing it already. Thanks.

How to reproduce
================
<How to reproduce the issue, or remove section if not relevant>

Has it worked previously?
=========================
<Is this a first attempt at getting the sample application to run, or has it worked in the past?>

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:
 
 - [ ] Verified that port 9093 is not blocked by firewall
 - [ ] Verified the namespace is either Standard or Dedicated tier (i.e. it is not Basic tier, which isn't supported)
 - [ ] Sample you're having trouble with: `<REPLACE with e.g., Java quickstart>`
 - [x] Apache Kafka version: `<REPLACE with e.g., 1.1.0>`
 - [ ] Kafka client configuration: `<REPLACE with e.g., auto.reset.offset=earliest, ..>` (*do not include your connection string or SAS Key*)
 - [ ] Namespace and EventHub/topic name
 - [ ] Consumer or producer failure `<REPLACE with e.g., Consumer failure>`
 - [ ] If consumer, partition ID, group ID `<REPLACE with e.g., partitionID=3, groupID=consumer-group>`
 - [ ] Timestamp in UTC `<REPLACE wtih e.g., Nov 7 2018 - 17:15:01 UTC>`
 - [ ] Client ID `<REPLACE with e.g., clientID=kafka-client>`
 - [ ] Provide all logs (with debugging enabled if possible) or exception call stack
 - [ ] Standalone repro `<REPLACE with e.g., Willing/able to send scenario to repro issue>`
 - [ ] Operating system: `<REPLACE with e.g., Ubuntu 16.04.5 (x64) LTS>`
 - [ ] Critical issue

**Comment by arerlend** [comment]
I can try this out when I have a few minutes to spare.

Are you using the arnaud librdkafka library?

**Comment by robert-schmidt** [comment]
Yes! But I am free to use whatever it works! Many thanks!

**Comment by robert-schmidt** [comment]
I managed to authenticate AND properly consume from an event hub. 

I'm posting my confs for others that might end up looking for hope here.

ENV: PHP 7.2
Kafka library used: https://github.com/arnaud-lb/php-rdkafka (look for consumer/producer examples on this repo). Make sure you install the librdkafka library first. For IDE, this composer package might prove useful as well: kwn/php-rdkafka-stubs.


`$conf = new \RdKafka\Conf();
$conf->set('group.id', 'your-consumer-group-name');
$conf->set('metadata.broker.list', 'sp-event-hubs.servicebus.windows.net:9093');
$conf->set('security.protocol', 'SASL_SSL');
$conf->set('sasl.mechanisms', 'PLAIN');
$conf->set('sasl.username', '$ConnectionString'); // exactly as you see it
$conf->set('sasl.password', 'Endpoint-string-from-azure'); // should look like: Endpoint=sb://sp-event-hubs.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=someStringHere
$conf->set('ssl.ca.location', '/absolute/path/to/cert.pem');
// This part was very confusing. Azure doesn't require any SSL cert for the SASL protocol, but authentication fails without using one. I finally got the cert from here: https://curl.haxx.se/docs/caextract.html, according to instructions from here: https://notetoself.tech/2018/06/03/acessing-event-hubs-with-confluent-kafka-library/
`
7 blessings :)

**Comment by arerlend** [comment]
Great, thanks @robert-schmidt 

I'll turn this into documentation whenever I have the chance.

**Comment by anantmaks** [comment]
@robert-schmidt  
As per your commented solution, I tried to use and consume a topic but it came out with no luck. Can you please have a look at the code and guide what needs to be done? 

I have installed the rdkafka.so on my ubuntu system as per [PHP Manual](https://arnaud.le-blanc.net/php-rdkafka-doc/phpdoc/index.html) and then used this piece of code :

`$conf = new RdKafka\Conf();`
`$conf->set('group.id', '$Default');`
`$conf->set('metadata.broker.list', 'syndigo-wk.servicebus.windows.net:9093');`
`$conf->set('security.protocol', 'SASL_SSL');`
`$conf->set('sasl.mechanisms', 'PLAIN');`
`$conf->set('sasl.username', '$ConnectionString');`
`$conf->set('sasl.password', 'const connectionString = "Endpoint=sb://syndigo-wk.servicebus.windows.net/;SharedAccessKeyName=syn-wk;SharedAccessKey=7K3RFuz6OEVXejb99PpyRRkmn8xXV9/8sncpnY4TosE=;EntityPath=webkul-syndigo"');`
`\\$conf->set('ssl.ca.location', 'http://localhost/azurekafka/cacert.pem');`
`$conf->set('api.version.request', 'false');`
`$conf->set('log_level', (string) LOG_DEBUG);`
`$conf->set('debug', 'all');`

`$rk = new RdKafka\Consumer($conf);`
`$topicConf = new RdKafka\TopicConf();`
`$topicConf->set('auto.commit.interval.ms', 100);`
`$topicConf->set('offset.store.method', 'broker');`
`$topicConf->set('auto.offset.reset', 'earliest');`
`$topic = $rk->newTopic("test", $topicConf);`

`while (true) {`
`    $message = $topic->consume(0, 120*10000);`
`    switch ($message->err) {`
`        case RD_KAFKA_RESP_ERR_NO_ERROR:`
`            var_dump($message);`
`            break;`
`        case RD_KAFKA_RESP_ERR__PARTITION_EOF:`
`            echo "No more messages; will wait for more\n";`
`            break;`
`        case RD_KAFKA_RESP_ERR__TIMED_OUT:`
`            echo "Timed out\n";`
`            break;`
`        default:`
`            throw new \Exception($message->errstr(), $message->err);`
`            break;`
`    }`
`}`

My connection string already has produced events in it that I can confirm by [azure-sdk-for-js](https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/eventhub/event-hubs/samples/v5/javascript), using JS SDK I am able to produce and consume events.
When I try to read the `$message` from `$topic` it returns as `null`

PS: 
1. I am currently using the pricing tier as 'Standard' on the azure event hub and it has Kafka Surface 'enabled'
2. I have tried setting `api.version.request` as 'true' as well
3. I have to comment `\\$conf->set('ssl.ca.location', 'http://localhost/azurekafka/cacert.pem');` as it is showing error _Fatal error: Uncaught RdKafka\Exception: ssl.ca.location failed: ../crypto/x509/by_file.c:199: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib: in /home/users/anant.garg/www/html/azurekafka/php-rdkafka-6.x/connect.php_ 
4. I have also tried to put the cert file over a live server and provided URI of that, but still the same error comes
