### ISSUE TITLE
SASL_PLAINTEXT Configuration

### ISSUE THREAD

**Issue by shekhar2709** [Azure/azure-event-hubs-for-kafka#52]
Description
===========

security.protocol=SASL_PLAINTEXT option not available.

Why SASL_PLAINTEXT option is not available. In my configuration, I do not provide any SSL certificates, so ideally I should set security.protocol=SASL_PLAINTEXT, but this does not works. I have to set to SASL_SSL to make it work.

How to reproduce
================
setting below configs(replaced namespace and others with appropriate values).

bootstrap.servers=mynamespace.servicebus.windows.net:9093
request.timeout.ms=60000
security.protocol=SASL_PLAINTEXT
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="{YOUR.EVENTHUBS.CONNECTION.STRING}";

Has it worked previously?
=========================

It did not.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:
 
 - [Y ] Verified that port 9093 is not blocked by firewall
 - [ Y] Verified the namespace is either Standard or Dedicated tier (i.e. it is not Basic tier, which isn't supported)
 - [ N] Sample you're having trouble with: `<REPLACE with e.g., Java quickstart>`
 - [2.1.0] Apache Kafka version: `<REPLACE with e.g., 1.1.0>`
 - [ X] Kafka client configuration: `<REPLACE with e.g., auto.reset.offset=earliest, ..>` (*do not include your connection string or SAS Key*)
 - [X ] Namespace and EventHub/topic name
 - [ X] Consumer or producer failure `<REPLACE with e.g., Consumer failure>`
 - [ X] If consumer, partition ID, group ID `<REPLACE with e.g., partitionID=3, groupID=consumer-group>`
 - [ ]X Timestamp in UTC `<REPLACE wtih e.g., Nov 7 2018 - 17:15:01 UTC>`
 - [ X] Client ID `<REPLACE with e.g., clientID=kafka-client>`
 - [X ] Provide all logs (with debugging enabled if possible) or exception call stack
 - [ X] Standalone repro `<REPLACE with e.g., Willing/able to send scenario to repro issue>`
 - [ Ubuntu] Operating system: `<REPLACE with e.g., Ubuntu 16.04.5 (x64) LTS>`
 - [ Yes] Critical issue

**Comment by shekhar2709** [comment]
Additionally, any other sasl mechanism other than sasl.mechanism=PLAIN, does not work.
Please suggest. I could not find any document with these restrictions.

**Comment by arerlend** [comment]
Event Hubs only allows SASL/PLAIN.  We do not allow connection without SSL encryption (SASL plaintext).  Is there a reason why SASL/PLAIN doesn't work for your use case?

Some light reading here: https://tools.ietf.org/html/rfc4616

On your additional questions: 

1. At the moment, we only support SASL/PLAIN - it's a basic auth mechanism that most Kafka clients will support, and it allows us to use the connection string pattern for client auth.
2. This depends on the SDK/framework you're using.  JDK has its own built in truststore.  Some clients, such as those based on librdkafka, may require you to provide a path to a trusted root cert on your file system (typically I can go to the default Linux OpenSSL installation - e.g. ‘/usr/lib/ssl/certs/ca-certificates.crt’).  If you are working on a specific SDK, let me know and I'm happy to help you get SASL/PLAIN working.

We are looking into supporting other auth mechanisms in our next sprint if you have specific requests.  I will leave the issue open and attach a discussion label.

**Comment by shekhar2709** [comment]
Hi Arerlend,

Thanks for your help.

I am still confused. I now understand that SASL_SSL is required, but since I am not providing my own ssl certificates and its using some public certificates(as you mentioned for Linux OpenSSL), and which anyone can use. Does it really mean a secure encryption?

**Comment by arerlend** [comment]
SSL uses public key certificates (proof of the service's identity) to establish symmetric key encryption tunneling between your client and the EH service.  The client _then_ proves its identity using the SASL PLAIN mechanism over the secure tunnel to prevent third parties from snooping on your connection string.

This is a standard, highly secure, widely tested way to perform client authentication.  Obviously, you need to make sure you download and use public certificates form a trusted source.

**Comment by shekhar2709** [comment]
Thanks for the clarification. 

I will follow this ticket to get an update for support to other auth mechanisms.
