### ISSUE TITLE
kafka Mirror Maker :Error when sending message to topic

### ISSUE THREAD

**Issue by ravisunkara** [Azure/azure-event-hubs-for-kafka#54]
Description
===========
Running Confluent kafka Mirror maker to push the topic to Kafka Enabled Event Hub from on Premises.The producer side of the mirror maker is unable to connect to 
[2019-06-10 08:53:57,958] WARN [Producer clientId=mirror_maker_producer] Connection to node -1 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)

How to reproduce
================
Run Kafka Mirror Maker with Consumer and Producer configurations.

Has it worked previously?
=========================
No

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:
 
 - [x ] Verified that port 9093 is not blocked by firewall
 - [x ] Verified the namespace is either Standard or Dedicated tier (i.e. it is not Basic tier, which isn't supported)
 - [x ] Sample you're having trouble with: `<Kafka Mirror Maker>`
 - [x] Apache Kafka version: `<2.2.0>`
 - [x ] Kafka client configuration: `<bootstrap.servers={EVENTHUBS.FQDN}:9093
client.id=mirror_maker_producer
sasl.mechanism=PLAIN
security.protocol=SASL_SSL
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="{EVENTHUBS.CONNECTION.STRING};>`
 - [ x] Namespace and EventHub/topic name '<kafkamirrioringtest.servicebus.windows.net / mirror_test>'
 - [x ] Consumer or producer failure  'Producer Failure'
 - [ ] If consumer, partition ID, group ID `<REPLACE with e.g., partitionID=3, groupID=consumer-group>`
 - [x ] Timestamp in UTC `<[2019-06-10 08:53:57,958]>`
 - [ ] Client ID `mirror-maker-producer`
 - [ ] Provide all logs (with debugging enabled if possible) or exception call stack
 - [ ] Standalone repro `<REPLACE with e.g., Willing/able to send scenario to repro issue>`
 - [x ] Operating system: `>Linux 3.10.0-514.26.2.el7.x86_64>`
 - [ ] Critical issue

**Comment by arerlend** [comment]
This error means that your configuration is probably wrong and your client can't find the broker.

When you look on the Azure portal, do you see requests hitting your event hub?

**Comment by ravisunkara** [comment]
> This error means that your configuration is probably wrong and your client can't find the broker.
> 
> When you look on the Azure portal, do you see requests hitting your event hub?

I dont see any incoming requests in Azure

**Comment by arerlend** [comment]
Are you able to run `ping kafkamirrioringtest.servicebus.windows.net` and get the domain name to resolve? You should see `Pinging ns-eh2-prod-by3-512.cloudapp.net [40.112.242.0] with 32 bytes of data:....`

**Comment by ravisunkara** [comment]
> Are you able to run `ping kafkamirrioringtest.servicebus.windows.net` and get the domain name to resolve? You should see `Pinging ns-eh2-prod-by3-512.cloudapp.net [40.112.242.0] with 32 bytes of data:....`

I am unable to ping the host
ping kafkamirrioringtest.servicebus.windows.net
PING ns-eh2-prod-by3-512.cloudapp.net (40.112.242.0): 56 data bytes
Request timeout for icmp_seq 0

**Comment by basilhariri** [comment]
This is definitely a network connectivity issue then. Until you can ping the FQDN and get the domain to resolve, you won't be able to connect to your Event Hub. I would check out your network settings (firewall is the usual culprit), and figure out why you can't connect.
