### ISSUE TITLE
TimeoutException in producer

### ISSUE THREAD

**Issue by mielmat** [Azure/azure-event-hubs-for-kafka#66]
Description
===========
I'm not sure if it is a place where should I ask about my problem, but I will try.
During testing system, I tried to send about 8 milions of events to one of our Event Hub with Kafka support enabled. About 40% of them failed because of: 

`Failed to send; nested exception is org.apache.kafka.common.errors.TimeoutException: Expiring 98 record(s) for topic-1: 71255 ms has passed since last append`

Has it worked previously?
=========================
Tests are run after migrating from HDInsight Kafka to EventHub Kafka

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:
 
 - [x] Verified that port 9093 is not blocked by firewall
 - [x] Verified the namespace is either Standard or Dedicated tier (i.e. it is not Basic tier, which isn't supported)
 - [ ] Sample you're having trouble with: `<REPLACE with e.g., Java quickstart>`
 - [x] Apache Kafka version: `2.0.0`
 - [x] Kafka client configuration: 
`batch,size=51200 
linger.ms=5000 
max.block.ms=90000 
request.timeout.ms=60000 
max.in.flight.request.per.connection=1
`
 - [ ] Namespace and EventHub/topic name
 - [x] Consumer or producer failure `Producer`
 - [ ] Timestamp in UTC `Aug 20 2019 - 06:55:33 UTC>`
 - [ ] Client ID `<REPLACE with e.g., clientID=kafka-client>`
 - [x] Provide all logs (with debugging enabled if possible) or exception call stack
 - [x] Operating system: `Ubuntu 18.04`
 - [ ] Critical issue

**Comment by arerlend** [comment]
@mielmat can you provide namespace info?

**Comment by mielmat** [comment]
Sorry for late answer, I already removed Event Hub before your comment. Microsoft Support was not able to help me. For now I moved from Event Hub with to Kafka to HDInsight cluster.

**Comment by arerlend** [comment]
Sorry about the late response @mielmat - let me know if you try EH Kafka again in the future.  I have some ideas about what may have gone wrong in the test.  Feel free to email me directly as well.

**Comment by prakashse7en** [comment]
@arelend we are facing similar issues we are using default values for batch,size,linger.ms,max.block.ms, request.timeout.ms, what should be done from our side could you pls help

**Comment by tomaszszlek** [comment]
Hi @arerlend, same issue occurs for us. Timeout didn't occur earlier with HD Insight.
Are there any advice what we can cause it ?

**Comment by mielmat** [comment]
@arerlend we started work with EH once again and problem still occurs - can you give some hints about that?

**Comment by mielmat** [comment]
ok @arerlend , we found your answer on SO: https://stackoverflow.com/a/58385324/5620649 and it looks like it resolves that issue.

**Comment by arerlend** [comment]
Great.  There is also a CONFIGURATION.md document that you can reference at the top level of this repo.
