### ISSUE TITLE
Example of Active Directory authentication missing

### ISSUE THREAD

**Issue by tblondelle** [Azure/azure-event-hubs-for-kafka#76]
Description
===========
The Active Directory authentication is the recommended approach when it comes to Event Hubs rather that SAS signature-based. How can I provide SPN credentials (tenant_id, client_id, client_secret) to a Kafka application so it can communicate with Event Hubs?

Has it worked previously?
=========================
No

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed or where adequate information has not been provided.

Please provide the relevant information for the following items:
 - [x] SDK (include version info): `Kafka for Java:latest`
 - [x] Sample you're having trouble with: `Java quickstart`
 - [ ] If using Apache Kafka Java clients or a framework that uses Apache Kafka Java clients, version:
 - [ ] Kafka client configuration: <REPLACE with e.g., auto.reset.offset=earliest, ..> (*do not include your connection string or SAS Key*)
 - [ ] Namespace and EventHub/topic name
 - [ ] Consumer or producer failure `<REPLACE with e.g., Consumer failure>`
 - [ ] Timestamps *in UTC* `<REPLACE with e.g., Nov 7 2018 - 17:15:01 UTC>`
 - [ ] group.id or client.id `<REPLACE with e.g., group.id=cg-name>`
 - [ ] Logs provided (with debug-level logging enabled if possible, e.g. log4j.rootLogger=DEBUG) or exception call stack
 - [ ] Standalone repro `<REPLACE with e.g., Willing/able to send scenario to repro issue>`
 - [ ] Operating system: `<REPLACE with e.g., Ubuntu 16.04.5 (x64) LTS>`
 - [x] Critical issue: `No`

If this is a question on basic functionality, please verify the following:
 - [x] Port 9093 should not be blocked by firewall ("broker cannot be found" errors)
 - [x] Pinging FQDN shoudl return cluster DNS resolution (e.g. `$ ping namespace.servicebus.windows.net` returns ~ `ns-eh2-prod-am3-516.cloudapp.net [13.69.64.0]`)
 - [x] Namespace should be either Standard or Dedicated tier, not Basic (TopicAuthorization errors)

**Comment by arerlend** [comment]
Service changes + docs/sample code are in review.  I'll bump this thread when released.

**Comment by serkantkaraca** [comment]
OAuth samples checked-in under tutorials.
