### ISSUE TITLE
org.apache.kafka.common.errors.TopicAuthorizationException: Not authorized to access topics: 

### ISSUE THREAD

**Issue by sravankreddy** [Azure/azure-event-hubs-for-kafka#78]
Description
===========
I am getting topic authorization excepiton with producer code. below are my configs

 properties.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "XXXX.servicebus.windows.net:9093");
  properties.put("security.protocol", "SASL_SSL");  
  properties.put("sasl.mechanism", "PLAIN"); 
  properties.put("sasl.jaas.config",
      "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"$ConnectionString\" password=\"Endpoint=sb://XXXX.servicebus.windows.net/;SharedAccessKeyName=XXXX;SharedAccessKey=XXX\";")

Has it worked previously?
=========================
Yes, it worked previously but from last 5 days not working

Topic is getting created but  not able to push messages.

**Comment by arerlend** [comment]
Please fill out the issue checklist.  I can't help if I don't know your namespace.

**Comment by arerlend** [comment]
@sravankreddy bump

**Comment by arerlend** [comment]
Stale.
