### ISSUE TITLE
sarama go client fails on fetch offset for non-existent offsets [for tracking purposes]

### ISSUE THREAD

**Issue by arerlend** [Azure/azure-event-hubs-for-kafka#85]
FOR TRACKING PURPOSES.

Description
===========
A retry mechanism was removed and partitions with no stored offsets or only expired offsets had nothing returned.

Has it worked previously?
=========================
Yes.  

_Fix is tested and ready for deployment.  This issue will be closed once the fix reaches deployment._

**Comment by geneccx** [comment]
Any ETA on this? Been watching https://github.com/Shopify/sarama/issues/1540 and it still appears to be an issue.

**Comment by arerlend** [comment]
Sorry for the delay - deployment had to be paused for the holidays but has been resumed.  If you have specific namespaces that need to be patched, you can ping me directly.

**Comment by arerlend** [comment]
Leaving this open for a few more days - the deployment was completed but had to be rolled back on a a few clusters, as there was an unrelated regression that affected a few customers.  Please ping directly if you are still seeing this issue.

**Comment by arerlend** [comment]
Closing.  Fix is deployed.

**Comment by davidandradeduarte** [comment]
I've forked sarama and added the following workaround (previously mentioned on this thread https://github.com/Shopify/sarama/pull/1542) and it works https://github.com/davidandradeduarte/sarama/commit/c2258cbf425a06a85212a4fd2c065f6e2c9feb4d
