### ISSUE TITLE
Where are the offsets stored when using Kafka Consumer Group?

### ISSUE THREAD

**Issue by prashanta** [Azure/azure-event-hubs-for-kafka#86]
Description
===========
Where are the consumer offsets stored internally by Event Hub when consuming Event Hub messages using Kafka Consumer (node-rdkafka)? When using EPH, the offsets are stored in Storage Account blob, but I don't see any container that is related to my Kafka Consumers Group (group.id config in Kafka Consumer). 
Is there a way to remove/reset offset of Consumer Groups on EH when using Kafka Consumer Group?

**Comment by arerlend** [comment]
Kafka offsets are stored opaquely by EH, you can't manage or see them the same way you can view offsets in a storage account with EPH.

You can use the DeleteGroups API to remove a Kafka consumer group in EH.  The kafka-consumer-groups utility '--delete' option uses this API.

More info on EH vs Kafka consumer group differences here: https://github.com/Azure/azure-event-hubs-for-kafka#more-faq

**Comment by arerlend** [comment]
I've closed the issue since there's nothing to be fixed, but feel free to keep asking if you need clarification.

**Comment by prashanta** [comment]
Thanks @arerlend for your response, cleared up all my questions regarding consumer groups!

**Comment by Leonardo-Ferreira** [comment]
well... I deleted my consumer group and created another one with the same name... but it appears that the offset is still there...
