### ISSUE TITLE
Can not connect to Azure EventHub instance using Go client

### ISSUE THREAD

**Issue by mehdimirabian** [Azure/azure-event-hubs-for-kafka#88]
Description
===========
Our deployment stopped working with the following error at exactly Jan, 6th 9:00pm PST:

{"error":"kafka: client has run out of available brokers to talk to (Is your cluster reachable?)","id":"39a4f074-c0f2-4664-991a-769f6ed28db6","level":"fatal","message":"couldn't establish connection to kafka","ts":1578595531249}
I tried re-creating consumergroups but nothing works anymore. Is this related?

How to reproduce
================
Try to connect to Kafka in runtime.

Has it worked previously?
=========================
It has worked previously

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed or where adequate information has not been provided.

Please provide the relevant information for the following items:
 - [ ] SDK (include version info): /Shopify/sarama v1.24.1
 - [ ] Sample you're having trouble with: Setting up azure eventhub
 - [x] If using Apache Kafka Java clients or a framework that uses Apache Kafka Java clients, version: `<REPLACE with e.g., 1.1.0>`
 - [ ] Kafka client configuration: 
	config := sarama.NewConfig()

	config.Net.SASL.Enable = true
	config.Net.SASL.User = "$ConnectionString"
	config.Net.SASL.Password = connectionString
	config.Net.SASL.Mechanism = "PLAIN"
	config.Net.TLS.Enable = true
	config.Net.TLS.Config = &tls.Config{}
	config.Version = sarama.V1_0_0_0
	config.Consumer.Offsets.CommitInterval = time.Second * time.Duration(commitInterval)
	config.ChannelBufferSize = 1e6
	config.ClientID = consumerGroup

	return sarama.NewConsumerGroup([]string{fmt.Sprintf("%s:9093", host)}, consumerGroup, config)
}
 - [ ] Namespace and EventHub/topic name: Namespace: int .  EventHub: queue-exve-srti-ece-int
 - [ ] Consumer or producer failure: Consumer failure
 - [ ] Timestamps *in UTC* Thursday, January 9, 2020 6:45:31.249 PM
 - [ ] group.id or client.id: persistence
 - [ ] Logs provided: "error":"kafka: client has run out of available brokers to talk to (Is your cluster reachable?
 - [ ] Standalone repro No
 - [ ] Operating system: debian10
 - [ ] Critical issue Yes

If this is a question on basic functionality, please verify the following:
 - [ ] Port 9093 should not be blocked by firewall ("broker cannot be found" errors)
 - [ ] Pinging FQDN shoudl return cluster DNS resolution (e.g. `$ ping namespace.servicebus.windows.net` returns ~ `ns-eh2-prod-am3-516.cloudapp.net [13.69.64.0]`)
 - [ ] Namespace should be either Standard or Dedicated tier, not Basic (TopicAuthorization errors)

**Comment by arerlend** [comment]
@mehdimirabian are you still seeing this issue?
