### ISSUE TITLE
Schema Registry support

### ISSUE THREAD

**Issue by hbensalem** [Azure/azure-event-hubs-for-kafka#90]
Could you please give us some visibility on the roadmap. When will EventHubs support storing the metadata of the schemas?

Thank you.

**Comment by arerlend** [comment]
@sjkwak

**Comment by PawaritL** [comment]
+1, would be extremely useful

**Comment by arerlend** [comment]
https://docs.microsoft.com/en-us/azure/event-hubs/schema-registry-overview

https://github.com/Azure/azure-schema-registry-for-kafka

**Comment by arerlend** [comment]
It's here!  Deployments are currently rolling out to clusters.

**Comment by arerlend** [comment]
Closing the issue since public preview should now be usable in all regions

**Comment by arerlend** [comment]
aka.ms/schemaregistry
