### ISSUE TITLE
How does Kafka offsets map to Event Hub checkpointing

### ISSUE THREAD

**Issue by GeeWee** [Azure/azure-event-hubs-for-kafka#92]
Description
===========
Perhaps it would be nice with a description of how Kafka offsets map to Event Hub checkpointing if at all.

It says
```
Kafka consumer groups are...
    - auto-created.
    - capable of storing offsets in the Event Hubs service.
```

Does this mean that using the Kafka enabled Event Hub does *not* use checkpointing like the EventProcessorHost, but rather keeps the offsets internally in the Event Hub service?

If this is correct, is there any sort of storage costs in relation to this?

**Comment by GeeWee** [comment]
It seems like the answer is in #86.

Feel free to close this if you think the documentation is adequate.

**Comment by arerlend** [comment]
@geewee thanks for the issue, sorry it wasn't clear.  Updated the docs in commit https://github.com/Azure/azure-event-hubs-for-kafka/commit/1200caeb06cc4bbbdbd8387464f0cab05439c34f.

**Comment by GeeWee** [comment]
Just want to say that those docs updated are much clearer, helpful and answered some unrelated things I had also been wondering. Great job.
