### ISSUE TITLE
Consumer group list not correct

### ISSUE THREAD

**Issue by eigakow** [Azure/azure-event-hubs-for-kafka#95]
Description
===========

Currently my Event Hub namespace consists of 3 Event Hubs. I am trying to fetch offsets for one of the kafka consumer groups present in one of the Event Hubs. However the consumer group I am interested in is not in the list fetched from Event Hub (however it is there visible through portal)

```
./kafka_2.12-2.3.0/bin/kafka-consumer-groups.sh --command-config consumer.properties --list --bootstrap-server tb349fr24.servicebus.windows.net:9093
testing_group
```

The 'testing_group' is indeed in one of the Event Hubs, but there are a few more not listed.
I have tried using connection strings defined both on Namespace and on EventHub level, with no difference. This is in itself a strange behaviour, as the consumer group listed is that case still listed even though I am connecting with permissions limited to a different EventHub.

Should the EventHub/topic be somehow specified in the request? If yes, how can I achieve that?

How to reproduce
================
Try listing all the consumer groups on a namespace with multiple event hubs/topics

Has it worked previously?
=========================
First attempt

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed or where adequate information has not been provided.

Please provide the relevant information for the following items:
 - [ ] SDK (include version info): `kafka_2.12-2.3.0`
 - [ ] Sample you're having trouble with: `kafka-consumer-groups.sh`
 - [x] If using Apache Kafka Java clients or a framework that uses Apache Kafka Java clients, version: `kafka_2.12-2.3.0`
 - [ ] Kafka client configuration: `security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="XXX";`
 - [ ] Namespace and tb349fr24/myfr24flow
 - [ ] Consumer or producer failure `Consumer group failure`
 - [ ] Timestamps *in UTC* ` 21 February 2020, 16:30:30 UTC`
 - [ ] group.id or client.id `group.id=test`
 - [ ] Operating system: `CentOS Linux release 7.5.1804 (Core)`

If this is a question on basic functionality, please verify the following:
 - [x] Port 9093 should not be blocked by firewall ("broker cannot be found" errors)
 - [x] Pinging FQDN shoudl return cluster DNS resolution (e.g. `$ ping namespace.servicebus.windows.net` returns ~ `ns-eh2-prod-am3-516.cloudapp.net [13.69.64.0]`)
 - [x] Namespace should be either Standard or Dedicated tier, not Basic (TopicAuthorization errors)

**Comment by turbo-ele** [comment]
same issue with SDK `kafka_2.12-2.4.0`

interesting observation: while only the consumer group(s) of one eventhub are listed, the azure metrics for the other eventhubs are showing some requests.

**Comment by arerlend** [comment]
Consumer groups visible in portal are EH/AMQP consumer groups.  Kafka consumer groups are not visible in portal.  If you are seeing consumer groups in the portal, they will not show up in your Kafka ListGroups call.

Kafka groups span the namespace to allow multi-topic subs, so you do not specify topics when listing groups.  But I would agree that if you are using an _topic-level_ SAS key, you should be blocked from committing (if not both fetch+commit) offsets for any consumer group on _unauthorized_ topics.  We will look into a behavior change there.

Thanks for opening the issue.
